/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.AccountRecipientIsCompany;
import com.example.transformation.dto.visa.CompanyRecipientIdentificationListAccountInner;
import com.example.transformation.dto.visa.RecipientAccountPayoutAddress1;
import com.example.transformation.dto.visa.RecipientIsIndividual1;
import com.example.transformation.dto.visa.Type;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.example.transformation.dto.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
@JsonDeserialize(using = AccountRecipientTransactorDetailWithID1.AccountRecipientTransactorDetailWithID1Deserializer.class)
@JsonSerialize(using = AccountRecipientTransactorDetailWithID1.AccountRecipientTransactorDetailWithID1Serializer.class)
public class AccountRecipientTransactorDetailWithID1 extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(AccountRecipientTransactorDetailWithID1.class.getName());

    public static class AccountRecipientTransactorDetailWithID1Serializer extends StdSerializer<AccountRecipientTransactorDetailWithID1> {
        public AccountRecipientTransactorDetailWithID1Serializer(Class<AccountRecipientTransactorDetailWithID1> t) {
            super(t);
        }

        public AccountRecipientTransactorDetailWithID1Serializer() {
            this(null);
        }

        @Override
        public void serialize(AccountRecipientTransactorDetailWithID1 value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class AccountRecipientTransactorDetailWithID1Deserializer extends StdDeserializer<AccountRecipientTransactorDetailWithID1> {
        public AccountRecipientTransactorDetailWithID1Deserializer() {
            this(AccountRecipientTransactorDetailWithID1.class);
        }

        public AccountRecipientTransactorDetailWithID1Deserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public AccountRecipientTransactorDetailWithID1 deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize AccountRecipientIsCompany
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (AccountRecipientIsCompany.class.equals(Integer.class) || AccountRecipientIsCompany.class.equals(Long.class) || AccountRecipientIsCompany.class.equals(Float.class) || AccountRecipientIsCompany.class.equals(Double.class) || AccountRecipientIsCompany.class.equals(Boolean.class) || AccountRecipientIsCompany.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((AccountRecipientIsCompany.class.equals(Integer.class) || AccountRecipientIsCompany.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((AccountRecipientIsCompany.class.equals(Float.class) || AccountRecipientIsCompany.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (AccountRecipientIsCompany.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (AccountRecipientIsCompany.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(AccountRecipientIsCompany.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'AccountRecipientIsCompany'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'AccountRecipientIsCompany'", e);
            }

            // deserialize RecipientIsIndividual1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (RecipientIsIndividual1.class.equals(Integer.class) || RecipientIsIndividual1.class.equals(Long.class) || RecipientIsIndividual1.class.equals(Float.class) || RecipientIsIndividual1.class.equals(Double.class) || RecipientIsIndividual1.class.equals(Boolean.class) || RecipientIsIndividual1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((RecipientIsIndividual1.class.equals(Integer.class) || RecipientIsIndividual1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((RecipientIsIndividual1.class.equals(Float.class) || RecipientIsIndividual1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (RecipientIsIndividual1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (RecipientIsIndividual1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(RecipientIsIndividual1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'RecipientIsIndividual1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'RecipientIsIndividual1'", e);
            }

            if (match == 1) {
                AccountRecipientTransactorDetailWithID1 ret = new AccountRecipientTransactorDetailWithID1();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for AccountRecipientTransactorDetailWithID1: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public AccountRecipientTransactorDetailWithID1 getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "AccountRecipientTransactorDetailWithID1 cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public AccountRecipientTransactorDetailWithID1() {
        super("oneOf", Boolean.FALSE);
    }

    public AccountRecipientTransactorDetailWithID1(AccountRecipientIsCompany o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public AccountRecipientTransactorDetailWithID1(RecipientIsIndividual1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("AccountRecipientIsCompany", AccountRecipientIsCompany.class);
        schemas.put("RecipientIsIndividual1", RecipientIsIndividual1.class);
        JSON.registerDescendants(AccountRecipientTransactorDetailWithID1.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return AccountRecipientTransactorDetailWithID1.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * AccountRecipientIsCompany, RecipientIsIndividual1
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(AccountRecipientIsCompany.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(RecipientIsIndividual1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be AccountRecipientIsCompany, RecipientIsIndividual1");
    }

    /**
     * Get the actual instance, which can be the following:
     * AccountRecipientIsCompany, RecipientIsIndividual1
     *
     * @return The actual instance (AccountRecipientIsCompany, RecipientIsIndividual1)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `AccountRecipientIsCompany`. If the actual instance is not `AccountRecipientIsCompany`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AccountRecipientIsCompany`
     * @throws ClassCastException if the instance is not `AccountRecipientIsCompany`
     */
    public AccountRecipientIsCompany getAccountRecipientIsCompany() throws ClassCastException {
        return (AccountRecipientIsCompany)super.getActualInstance();
    }

    /**
     * Get the actual instance of `RecipientIsIndividual1`. If the actual instance is not `RecipientIsIndividual1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RecipientIsIndividual1`
     * @throws ClassCastException if the instance is not `RecipientIsIndividual1`
     */
    public RecipientIsIndividual1 getRecipientIsIndividual1() throws ClassCastException {
        return (RecipientIsIndividual1)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof RecipientIsIndividual1) {
        if (getActualInstance() != null) {
          joiner.add(((RecipientIsIndividual1)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof AccountRecipientIsCompany) {
        if (getActualInstance() != null) {
          joiner.add(((AccountRecipientIsCompany)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

