/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.BalanceNotificationBalanceInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * BalanceNotification3
 */
@JsonPropertyOrder({
  BalanceNotification3.JSON_PROPERTY_BALANCE,
  BalanceNotification3.JSON_PROPERTY_ACCOUNT_ID,
  BalanceNotification3.JSON_PROPERTY_EVENT_TYPE,
  BalanceNotification3.JSON_PROPERTY_INITIATING_PARTY_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class BalanceNotification3 {
  public static final String JSON_PROPERTY_BALANCE = "balance";
  private List<BalanceNotificationBalanceInner> balance = new ArrayList<>();

  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  private String accountId;

  /**
   * Indicates why the balance notification is triggered  Possible values: * &#x60;THRESHOLD&#x60; - When balance threshold is exceeded * &#x60;LIQUIDITY_FAILURE&#x60; - when balance is negative * &#x60;PERIODIC&#x60; - Regular balance snapshot at certain day/time 
   */
  public enum EventTypeEnum {
    THRESHOLD("THRESHOLD"),
    
    LIQUIDITY_FAILURE("LIQUIDITY_FAILURE"),
    
    PERIODIC("PERIODIC");

    private String value;

    EventTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EventTypeEnum fromValue(String value) {
      for (EventTypeEnum b : EventTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  private EventTypeEnum eventType;

  public static final String JSON_PROPERTY_INITIATING_PARTY_ID = "initiatingPartyId";
  private Long initiatingPartyId;

  public BalanceNotification3() { 
  }

  public BalanceNotification3 balance(List<BalanceNotificationBalanceInner> balance) {
    this.balance = balance;
    return this;
  }

  public BalanceNotification3 addBalanceItem(BalanceNotificationBalanceInner balanceItem) {
    if (this.balance == null) {
      this.balance = new ArrayList<>();
    }
    this.balance.add(balanceItem);
    return this;
  }

  /**
   * array of balances for all currencies of the &#39;accountId&#39;
   * @return balance
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BALANCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<BalanceNotificationBalanceInner> getBalance() {
    return balance;
  }


  @JsonProperty(JSON_PROPERTY_BALANCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBalance(List<BalanceNotificationBalanceInner> balance) {
    this.balance = balance;
  }


  public BalanceNotification3 accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * The accountId uniquely identifies the ledger account as a virtual account number(i.e. VAN), with a value or number assigned by Visa.
   * @return accountId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccountId() {
    return accountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }


  public BalanceNotification3 eventType(EventTypeEnum eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * Indicates why the balance notification is triggered  Possible values: * &#x60;THRESHOLD&#x60; - When balance threshold is exceeded * &#x60;LIQUIDITY_FAILURE&#x60; - when balance is negative * &#x60;PERIODIC&#x60; - Regular balance snapshot at certain day/time 
   * @return eventType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EventTypeEnum getEventType() {
    return eventType;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventType(EventTypeEnum eventType) {
    this.eventType = eventType;
  }


  public BalanceNotification3 initiatingPartyId(Long initiatingPartyId) {
    this.initiatingPartyId = initiatingPartyId;
    return this;
  }

  /**
   * Identifier assigned by Visa to uniquely identify the Originating Entity who initiates the transaction  ISO20022 field name: &lt;InitgPtyId&gt; - InitiatingPartyIdentification, new identification of the initiating party. Visa uses integer instead of string(1-35) for uniformed value generation and presentation. 
   * @return initiatingPartyId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INITIATING_PARTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getInitiatingPartyId() {
    return initiatingPartyId;
  }


  @JsonProperty(JSON_PROPERTY_INITIATING_PARTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInitiatingPartyId(Long initiatingPartyId) {
    this.initiatingPartyId = initiatingPartyId;
  }


  /**
   * Return true if this BalanceNotification-3 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalanceNotification3 balanceNotification3 = (BalanceNotification3) o;
    return Objects.equals(this.balance, balanceNotification3.balance) &&
        Objects.equals(this.accountId, balanceNotification3.accountId) &&
        Objects.equals(this.eventType, balanceNotification3.eventType) &&
        Objects.equals(this.initiatingPartyId, balanceNotification3.initiatingPartyId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(balance, accountId, eventType, initiatingPartyId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalanceNotification3 {\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    initiatingPartyId: ").append(toIndentedString(initiatingPartyId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `balance` to the URL query string
    if (getBalance() != null) {
      for (int i = 0; i < getBalance().size(); i++) {
        if (getBalance().get(i) != null) {
          joiner.add(getBalance().get(i).toUrlQueryString(String.format("%sbalance%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `accountId` to the URL query string
    if (getAccountId() != null) {
      joiner.add(String.format("%saccountId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAccountId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `eventType` to the URL query string
    if (getEventType() != null) {
      joiner.add(String.format("%seventType%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getEventType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `initiatingPartyId` to the URL query string
    if (getInitiatingPartyId() != null) {
      joiner.add(String.format("%sinitiatingPartyId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getInitiatingPartyId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

