/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * BalanceNotificationBalanceInner
 */
@JsonPropertyOrder({
  BalanceNotificationBalanceInner.JSON_PROPERTY_AMOUNT,
  BalanceNotificationBalanceInner.JSON_PROPERTY_CURRENCY_CODE,
  BalanceNotificationBalanceInner.JSON_PROPERTY_OPERATOR,
  BalanceNotificationBalanceInner.JSON_PROPERTY_THRESHOLD,
  BalanceNotificationBalanceInner.JSON_PROPERTY_BALANCE_TIMESTAMP
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class BalanceNotificationBalanceInner {
  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private Double amount;

  public static final String JSON_PROPERTY_CURRENCY_CODE = "currencyCode";
  private String currencyCode;

  /**
   * This field only applies to &#39;THRESHOLD&#39; and &#39;LIQUIDITY_FAILURE&#39; eventType
   */
  public enum OperatorEnum {
    LESS_THAN("LESS_THAN");

    private String value;

    OperatorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperatorEnum fromValue(String value) {
      for (OperatorEnum b : OperatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OPERATOR = "operator";
  private OperatorEnum operator;

  public static final String JSON_PROPERTY_THRESHOLD = "threshold";
  private Double threshold;

  public static final String JSON_PROPERTY_BALANCE_TIMESTAMP = "balanceTimestamp";
  private OffsetDateTime balanceTimestamp;

  public BalanceNotificationBalanceInner() { 
  }

  public BalanceNotificationBalanceInner amount(Double amount) {
    this.amount = amount;
    return this;
  }

  /**
   * The balance amount for a particular currency.  Note: The number of decimal places assumed for this field depends on the currency. 
   * @return amount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Double getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(Double amount) {
    this.amount = amount;
  }


  public BalanceNotificationBalanceInner currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

  /**
   * The currency code is a three letter ISO 4217 code.   E.g. GBP for British sterling pounds. 
   * @return currencyCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurrencyCode() {
    return currencyCode;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  public BalanceNotificationBalanceInner operator(OperatorEnum operator) {
    this.operator = operator;
    return this;
  }

  /**
   * This field only applies to &#39;THRESHOLD&#39; and &#39;LIQUIDITY_FAILURE&#39; eventType
   * @return operator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OperatorEnum getOperator() {
    return operator;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperator(OperatorEnum operator) {
    this.operator = operator;
  }


  public BalanceNotificationBalanceInner threshold(Double threshold) {
    this.threshold = threshold;
    return this;
  }

  /**
   * This field only applies to &#39;THRESHOLD&#39; and &#39;LIQUIDITY_FAILURE&#39; eventType. Threshold value would be zero for LIQUIDITY_FAILURE eventType. 
   * minimum: 0
   * @return threshold
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getThreshold() {
    return threshold;
  }


  @JsonProperty(JSON_PROPERTY_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThreshold(Double threshold) {
    this.threshold = threshold;
  }


  public BalanceNotificationBalanceInner balanceTimestamp(OffsetDateTime balanceTimestamp) {
    this.balanceTimestamp = balanceTimestamp;
    return this;
  }

  /**
   * ISO 8601 formatted UTC Timestamp, YYYY-MM-DDThh:mm:ss.sssTZD. TZD is either Z or +/-00:00  example: 2020-05-05T12:12:12.000Z, or 1997-07-16T19:20:30.45+00:00  ISO20022 field name: Transaction Information And Status - Message Creation Date Time 
   * @return balanceTimestamp
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BALANCE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getBalanceTimestamp() {
    return balanceTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_BALANCE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBalanceTimestamp(OffsetDateTime balanceTimestamp) {
    this.balanceTimestamp = balanceTimestamp;
  }


  /**
   * Return true if this BalanceNotification_balance_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalanceNotificationBalanceInner balanceNotificationBalanceInner = (BalanceNotificationBalanceInner) o;
    return Objects.equals(this.amount, balanceNotificationBalanceInner.amount) &&
        Objects.equals(this.currencyCode, balanceNotificationBalanceInner.currencyCode) &&
        Objects.equals(this.operator, balanceNotificationBalanceInner.operator) &&
        Objects.equals(this.threshold, balanceNotificationBalanceInner.threshold) &&
        Objects.equals(this.balanceTimestamp, balanceNotificationBalanceInner.balanceTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, currencyCode, operator, threshold, balanceTimestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalanceNotificationBalanceInner {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    balanceTimestamp: ").append(toIndentedString(balanceTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(String.format("%samount%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAmount()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `currencyCode` to the URL query string
    if (getCurrencyCode() != null) {
      joiner.add(String.format("%scurrencyCode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCurrencyCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `operator` to the URL query string
    if (getOperator() != null) {
      joiner.add(String.format("%soperator%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getOperator()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `threshold` to the URL query string
    if (getThreshold() != null) {
      joiner.add(String.format("%sthreshold%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getThreshold()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `balanceTimestamp` to the URL query string
    if (getBalanceTimestamp() != null) {
      joiner.add(String.format("%sbalanceTimestamp%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getBalanceTimestamp()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

