/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * ExposureInfoDetails
 */
@JsonPropertyOrder({
  ExposureInfoDetails.JSON_PROPERTY_DUE_DATE_TIME,
  ExposureInfoDetails.JSON_PROPERTY_CURRENCY_CODE,
  ExposureInfoDetails.JSON_PROPERTY_TOTAL_AMOUNT_DUE,
  ExposureInfoDetails.JSON_PROPERTY_TOTAL_AMOUNT_OVERDUE,
  ExposureInfoDetails.JSON_PROPERTY_FLEXIBLE_AMOUNT_LIMIT,
  ExposureInfoDetails.JSON_PROPERTY_ORIGINAL_DUE_DATE_TIME,
  ExposureInfoDetails.JSON_PROPERTY_FLEXIBLE_AMOUNT_UTILIZED,
  ExposureInfoDetails.JSON_PROPERTY_FLEXIBLE_AMOUNT_REMAINING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class ExposureInfoDetails {
  public static final String JSON_PROPERTY_DUE_DATE_TIME = "dueDateTime";
  private OffsetDateTime dueDateTime;

  public static final String JSON_PROPERTY_CURRENCY_CODE = "currencyCode";
  private String currencyCode;

  public static final String JSON_PROPERTY_TOTAL_AMOUNT_DUE = "totalAmountDue";
  private Double totalAmountDue;

  public static final String JSON_PROPERTY_TOTAL_AMOUNT_OVERDUE = "totalAmountOverdue";
  private Double totalAmountOverdue;

  public static final String JSON_PROPERTY_FLEXIBLE_AMOUNT_LIMIT = "flexibleAmountLimit";
  private Double flexibleAmountLimit;

  public static final String JSON_PROPERTY_ORIGINAL_DUE_DATE_TIME = "originalDueDateTime";
  private OffsetDateTime originalDueDateTime;

  public static final String JSON_PROPERTY_FLEXIBLE_AMOUNT_UTILIZED = "flexibleAmountUtilized";
  private Double flexibleAmountUtilized;

  public static final String JSON_PROPERTY_FLEXIBLE_AMOUNT_REMAINING = "flexibleAmountRemaining";
  private Double flexibleAmountRemaining;

  public ExposureInfoDetails() { 
  }

  public ExposureInfoDetails dueDateTime(OffsetDateTime dueDateTime) {
    this.dueDateTime = dueDateTime;
    return this;
  }

  /**
   * ISO 8601 formatted UTC Timestamp, YYYY-MM-DDThh:mm:ss.sssTZD. TZD is either Z or +/-00:00  example: 2020-05-05T12:12:12.000Z, or 1997-07-16T19:20:30.45+00:00  ISO20022 field name: Transaction Information And Status - Message Creation Date Time 
   * @return dueDateTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DUE_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getDueDateTime() {
    return dueDateTime;
  }


  @JsonProperty(JSON_PROPERTY_DUE_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDueDateTime(OffsetDateTime dueDateTime) {
    this.dueDateTime = dueDateTime;
  }


  public ExposureInfoDetails currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

  /**
   * 3-character ISO-4217 (Alpha-3) currency code 
   * @return currencyCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurrencyCode() {
    return currencyCode;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  public ExposureInfoDetails totalAmountDue(Double totalAmountDue) {
    this.totalAmountDue = totalAmountDue;
    return this;
  }

  /**
   * Total amount due by due date.
   * @return totalAmountDue
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_AMOUNT_DUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTotalAmountDue() {
    return totalAmountDue;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_AMOUNT_DUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalAmountDue(Double totalAmountDue) {
    this.totalAmountDue = totalAmountDue;
  }


  public ExposureInfoDetails totalAmountOverdue(Double totalAmountOverdue) {
    this.totalAmountOverdue = totalAmountOverdue;
    return this;
  }

  /**
   * Total amount overdue.
   * @return totalAmountOverdue
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_AMOUNT_OVERDUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTotalAmountOverdue() {
    return totalAmountOverdue;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_AMOUNT_OVERDUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalAmountOverdue(Double totalAmountOverdue) {
    this.totalAmountOverdue = totalAmountOverdue;
  }


  public ExposureInfoDetails flexibleAmountLimit(Double flexibleAmountLimit) {
    this.flexibleAmountLimit = flexibleAmountLimit;
    return this;
  }

  /**
   * Liquidity limit.
   * @return flexibleAmountLimit
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FLEXIBLE_AMOUNT_LIMIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Double getFlexibleAmountLimit() {
    return flexibleAmountLimit;
  }


  @JsonProperty(JSON_PROPERTY_FLEXIBLE_AMOUNT_LIMIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlexibleAmountLimit(Double flexibleAmountLimit) {
    this.flexibleAmountLimit = flexibleAmountLimit;
  }


  public ExposureInfoDetails originalDueDateTime(OffsetDateTime originalDueDateTime) {
    this.originalDueDateTime = originalDueDateTime;
    return this;
  }

  /**
   * ISO 8601 formatted UTC Timestamp, YYYY-MM-DDThh:mm:ss.sssTZD. TZD is either Z or +/-00:00  example: 2020-05-05T12:12:12.000Z, or 1997-07-16T19:20:30.45+00:00  ISO20022 field name: Transaction Information And Status - Message Creation Date Time 
   * @return originalDueDateTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORIGINAL_DUE_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getOriginalDueDateTime() {
    return originalDueDateTime;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINAL_DUE_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOriginalDueDateTime(OffsetDateTime originalDueDateTime) {
    this.originalDueDateTime = originalDueDateTime;
  }


  public ExposureInfoDetails flexibleAmountUtilized(Double flexibleAmountUtilized) {
    this.flexibleAmountUtilized = flexibleAmountUtilized;
    return this;
  }

  /**
   * Amount of liquidity that has been utilized.
   * @return flexibleAmountUtilized
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FLEXIBLE_AMOUNT_UTILIZED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Double getFlexibleAmountUtilized() {
    return flexibleAmountUtilized;
  }


  @JsonProperty(JSON_PROPERTY_FLEXIBLE_AMOUNT_UTILIZED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlexibleAmountUtilized(Double flexibleAmountUtilized) {
    this.flexibleAmountUtilized = flexibleAmountUtilized;
  }


  public ExposureInfoDetails flexibleAmountRemaining(Double flexibleAmountRemaining) {
    this.flexibleAmountRemaining = flexibleAmountRemaining;
    return this;
  }

  /**
   * Remaining amount of liquidity available.
   * @return flexibleAmountRemaining
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FLEXIBLE_AMOUNT_REMAINING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Double getFlexibleAmountRemaining() {
    return flexibleAmountRemaining;
  }


  @JsonProperty(JSON_PROPERTY_FLEXIBLE_AMOUNT_REMAINING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlexibleAmountRemaining(Double flexibleAmountRemaining) {
    this.flexibleAmountRemaining = flexibleAmountRemaining;
  }


  /**
   * Return true if this ExposureInfoDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExposureInfoDetails exposureInfoDetails = (ExposureInfoDetails) o;
    return Objects.equals(this.dueDateTime, exposureInfoDetails.dueDateTime) &&
        Objects.equals(this.currencyCode, exposureInfoDetails.currencyCode) &&
        Objects.equals(this.totalAmountDue, exposureInfoDetails.totalAmountDue) &&
        Objects.equals(this.totalAmountOverdue, exposureInfoDetails.totalAmountOverdue) &&
        Objects.equals(this.flexibleAmountLimit, exposureInfoDetails.flexibleAmountLimit) &&
        Objects.equals(this.originalDueDateTime, exposureInfoDetails.originalDueDateTime) &&
        Objects.equals(this.flexibleAmountUtilized, exposureInfoDetails.flexibleAmountUtilized) &&
        Objects.equals(this.flexibleAmountRemaining, exposureInfoDetails.flexibleAmountRemaining);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dueDateTime, currencyCode, totalAmountDue, totalAmountOverdue, flexibleAmountLimit, originalDueDateTime, flexibleAmountUtilized, flexibleAmountRemaining);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExposureInfoDetails {\n");
    sb.append("    dueDateTime: ").append(toIndentedString(dueDateTime)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    totalAmountDue: ").append(toIndentedString(totalAmountDue)).append("\n");
    sb.append("    totalAmountOverdue: ").append(toIndentedString(totalAmountOverdue)).append("\n");
    sb.append("    flexibleAmountLimit: ").append(toIndentedString(flexibleAmountLimit)).append("\n");
    sb.append("    originalDueDateTime: ").append(toIndentedString(originalDueDateTime)).append("\n");
    sb.append("    flexibleAmountUtilized: ").append(toIndentedString(flexibleAmountUtilized)).append("\n");
    sb.append("    flexibleAmountRemaining: ").append(toIndentedString(flexibleAmountRemaining)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `dueDateTime` to the URL query string
    if (getDueDateTime() != null) {
      joiner.add(String.format("%sdueDateTime%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDueDateTime()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `currencyCode` to the URL query string
    if (getCurrencyCode() != null) {
      joiner.add(String.format("%scurrencyCode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCurrencyCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `totalAmountDue` to the URL query string
    if (getTotalAmountDue() != null) {
      joiner.add(String.format("%stotalAmountDue%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTotalAmountDue()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `totalAmountOverdue` to the URL query string
    if (getTotalAmountOverdue() != null) {
      joiner.add(String.format("%stotalAmountOverdue%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTotalAmountOverdue()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `flexibleAmountLimit` to the URL query string
    if (getFlexibleAmountLimit() != null) {
      joiner.add(String.format("%sflexibleAmountLimit%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFlexibleAmountLimit()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `originalDueDateTime` to the URL query string
    if (getOriginalDueDateTime() != null) {
      joiner.add(String.format("%soriginalDueDateTime%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getOriginalDueDateTime()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `flexibleAmountUtilized` to the URL query string
    if (getFlexibleAmountUtilized() != null) {
      joiner.add(String.format("%sflexibleAmountUtilized%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFlexibleAmountUtilized()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `flexibleAmountRemaining` to the URL query string
    if (getFlexibleAmountRemaining() != null) {
      joiner.add(String.format("%sflexibleAmountRemaining%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFlexibleAmountRemaining()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

