/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * MinTransactionAmountEquivalentInner
 */
@JsonPropertyOrder({
  MinTransactionAmountEquivalentInner.JSON_PROPERTY_CONDITION,
  MinTransactionAmountEquivalentInner.JSON_PROPERTY_MIN_AMOUNT_VALUE,
  MinTransactionAmountEquivalentInner.JSON_PROPERTY_CURRENCY_OF_MIN_AMOUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class MinTransactionAmountEquivalentInner {
  public static final String JSON_PROPERTY_CONDITION = "condition";
  private String condition;

  public static final String JSON_PROPERTY_MIN_AMOUNT_VALUE = "minAmountValue";
  private BigDecimal minAmountValue;

  public static final String JSON_PROPERTY_CURRENCY_OF_MIN_AMOUNT = "currencyOfMinAmount";
  private String currencyOfMinAmount;

  public MinTransactionAmountEquivalentInner() { 
  }

  public MinTransactionAmountEquivalentInner condition(String condition) {
    this.condition = condition;
    return this;
  }

  /**
   * It refers to an &#39;id&#39; value in the conditions[] array.
   * @return condition
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONDITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCondition() {
    return condition;
  }


  @JsonProperty(JSON_PROPERTY_CONDITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCondition(String condition) {
    this.condition = condition;
  }


  public MinTransactionAmountEquivalentInner minAmountValue(BigDecimal minAmountValue) {
    this.minAmountValue = minAmountValue;
    return this;
  }

  /**
   * The minimum amount value allowed per transaction.
   * @return minAmountValue
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MIN_AMOUNT_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getMinAmountValue() {
    return minAmountValue;
  }


  @JsonProperty(JSON_PROPERTY_MIN_AMOUNT_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMinAmountValue(BigDecimal minAmountValue) {
    this.minAmountValue = minAmountValue;
  }


  public MinTransactionAmountEquivalentInner currencyOfMinAmount(String currencyOfMinAmount) {
    this.currencyOfMinAmount = currencyOfMinAmount;
    return this;
  }

  /**
   * The (Alpha-3) ISO-4217 currency code of the minimum amount value allowed per transaction. This could be in recipient bank currency or in a more common currency like USD, EUR or GBP.
   * @return currencyOfMinAmount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURRENCY_OF_MIN_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurrencyOfMinAmount() {
    return currencyOfMinAmount;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY_OF_MIN_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrencyOfMinAmount(String currencyOfMinAmount) {
    this.currencyOfMinAmount = currencyOfMinAmount;
  }


  /**
   * Return true if this MinTransactionAmountEquivalent_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MinTransactionAmountEquivalentInner minTransactionAmountEquivalentInner = (MinTransactionAmountEquivalentInner) o;
    return Objects.equals(this.condition, minTransactionAmountEquivalentInner.condition) &&
        Objects.equals(this.minAmountValue, minTransactionAmountEquivalentInner.minAmountValue) &&
        Objects.equals(this.currencyOfMinAmount, minTransactionAmountEquivalentInner.currencyOfMinAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(condition, minAmountValue, currencyOfMinAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MinTransactionAmountEquivalentInner {\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    minAmountValue: ").append(toIndentedString(minAmountValue)).append("\n");
    sb.append("    currencyOfMinAmount: ").append(toIndentedString(currencyOfMinAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `condition` to the URL query string
    if (getCondition() != null) {
      joiner.add(String.format("%scondition%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCondition()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `minAmountValue` to the URL query string
    if (getMinAmountValue() != null) {
      joiner.add(String.format("%sminAmountValue%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMinAmountValue()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `currencyOfMinAmount` to the URL query string
    if (getCurrencyOfMinAmount() != null) {
      joiner.add(String.format("%scurrencyOfMinAmount%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCurrencyOfMinAmount()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

