/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * PayoutReturnRequestV2TransactionDetailReturnReasonDetails
 */
@JsonPropertyOrder({
  PayoutReturnRequestV2TransactionDetailReturnReasonDetails.JSON_PROPERTY_CODE,
  PayoutReturnRequestV2TransactionDetailReturnReasonDetails.JSON_PROPERTY_TYPE,
  PayoutReturnRequestV2TransactionDetailReturnReasonDetails.JSON_PROPERTY_DESCRIPTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class PayoutReturnRequestV2TransactionDetailReturnReasonDetails {
  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  /**
   * Indicates the return type when the payout is returned. &lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/capabilities/visa-direct-payouts/docs-error-codes\&quot;&gt;Return Type&lt;/a&gt;   ISO20022 field name: Payment Return - PSP Return Type
   */
  public enum TypeEnum {
    REJECT("REJECT"),
    
    RETURN("RETURN");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public PayoutReturnRequestV2TransactionDetailReturnReasonDetails() { 
  }

  public PayoutReturnRequestV2TransactionDetailReturnReasonDetails code(String code) {
    this.code = code;
    return this;
  }

  /**
   * Indicates the return reason code when the payout is returned.&lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/capabilities/visa-direct-payouts/docs-error-codes\&quot;&gt;RE Code&lt;/a&gt;   ISO20022 field name: Payment Return - Reason Code
   * @return code
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(String code) {
    this.code = code;
  }


  public PayoutReturnRequestV2TransactionDetailReturnReasonDetails type(TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Indicates the return type when the payout is returned. &lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/capabilities/visa-direct-payouts/docs-error-codes\&quot;&gt;Return Type&lt;/a&gt;   ISO20022 field name: Payment Return - PSP Return Type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(TypeEnum type) {
    this.type = type;
  }


  public PayoutReturnRequestV2TransactionDetailReturnReasonDetails description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Indicates the return description when the payout is returned. &lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/capabilities/visa-direct-payouts/docs-error-codes\&quot;&gt;Return Description&lt;/a&gt;   ISO20022 field name: Payment Return - PSP Return Description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  /**
   * Return true if this PayoutReturnRequestV2_transactionDetail_returnReasonDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayoutReturnRequestV2TransactionDetailReturnReasonDetails payoutReturnRequestV2TransactionDetailReturnReasonDetails = (PayoutReturnRequestV2TransactionDetailReturnReasonDetails) o;
    return Objects.equals(this.code, payoutReturnRequestV2TransactionDetailReturnReasonDetails.code) &&
        Objects.equals(this.type, payoutReturnRequestV2TransactionDetailReturnReasonDetails.type) &&
        Objects.equals(this.description, payoutReturnRequestV2TransactionDetailReturnReasonDetails.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, type, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayoutReturnRequestV2TransactionDetailReturnReasonDetails {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format("%scode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDescription()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

