/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.PayoutAccountRequestRecipientDetailIdentificationList;
import com.example.transformation.dto.visa.RecipientAccountPayoutAddress;
import com.example.transformation.dto.visa.RecipientAdditionalDataInner;
import com.example.transformation.dto.visa.Type;
import com.example.transformation.dto.visa.Wallet;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * PayoutWalletRequestRecipientDetail
 */
@JsonPropertyOrder({
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_WALLET,
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_CONTACT_EMAIL,
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_CONTACT_NUMBER,
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_ADDITIONAL_DATA,
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_CONTACT_NUMBER_TYPE,
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_IDENTIFICATION_LIST,
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_NAME,
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_TYPE,
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_ADDRESS,
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_LAST_NAME,
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_FIRST_NAME,
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_CITY_OF_BIRTH,
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_DATE_OF_BIRTH,
  PayoutWalletRequestRecipientDetail.JSON_PROPERTY_COUNTRY_OF_BIRTH
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class PayoutWalletRequestRecipientDetail {
  public static final String JSON_PROPERTY_WALLET = "wallet";
  private Wallet wallet;

  public static final String JSON_PROPERTY_CONTACT_EMAIL = "contactEmail";
  private String contactEmail;

  public static final String JSON_PROPERTY_CONTACT_NUMBER = "contactNumber";
  private String contactNumber;

  public static final String JSON_PROPERTY_ADDITIONAL_DATA = "additionalData";
  private List<RecipientAdditionalDataInner> additionalData = new ArrayList<>();

  /**
   * Gets or Sets contactNumberType
   */
  public enum ContactNumberTypeEnum {
    MOBILE("MOBILE"),
    
    WORK("WORK"),
    
    HOME("HOME");

    private String value;

    ContactNumberTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ContactNumberTypeEnum fromValue(String value) {
      for (ContactNumberTypeEnum b : ContactNumberTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CONTACT_NUMBER_TYPE = "contactNumberType";
  private ContactNumberTypeEnum contactNumberType;

  public static final String JSON_PROPERTY_IDENTIFICATION_LIST = "identificationList";
  private PayoutAccountRequestRecipientDetailIdentificationList identificationList;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_TYPE = "type";
  private Type type;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private RecipientAccountPayoutAddress address;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  private String lastName;

  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  private String firstName;

  public static final String JSON_PROPERTY_CITY_OF_BIRTH = "cityOfBirth";
  private String cityOfBirth;

  public static final String JSON_PROPERTY_DATE_OF_BIRTH = "dateOfBirth";
  private LocalDate dateOfBirth;

  public static final String JSON_PROPERTY_COUNTRY_OF_BIRTH = "countryOfBirth";
  private String countryOfBirth;

  public PayoutWalletRequestRecipientDetail() { 
  }

  public PayoutWalletRequestRecipientDetail wallet(Wallet wallet) {
    this.wallet = wallet;
    return this;
  }

  /**
   * Get wallet
   * @return wallet
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WALLET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Wallet getWallet() {
    return wallet;
  }


  @JsonProperty(JSON_PROPERTY_WALLET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWallet(Wallet wallet) {
    this.wallet = wallet;
  }


  public PayoutWalletRequestRecipientDetail contactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
    return this;
  }

  /**
   * Recipient email address  ISO20022 field name: Ultimate Creditor Contact Email Address 
   * @return contactEmail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTACT_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getContactEmail() {
    return contactEmail;
  }


  @JsonProperty(JSON_PROPERTY_CONTACT_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }


  public PayoutWalletRequestRecipientDetail contactNumber(String contactNumber) {
    this.contactNumber = contactNumber;
    return this;
  }

  /**
   * Recipient contact number + symbol followed by digits, no other symbols, e.g. +447700123456  
   * @return contactNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTACT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getContactNumber() {
    return contactNumber;
  }


  @JsonProperty(JSON_PROPERTY_CONTACT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContactNumber(String contactNumber) {
    this.contactNumber = contactNumber;
  }


  public PayoutWalletRequestRecipientDetail additionalData(List<RecipientAdditionalDataInner> additionalData) {
    this.additionalData = additionalData;
    return this;
  }

  public PayoutWalletRequestRecipientDetail addAdditionalDataItem(RecipientAdditionalDataInner additionalDataItem) {
    if (this.additionalData == null) {
      this.additionalData = new ArrayList<>();
    }
    this.additionalData.add(additionalDataItem);
    return this;
  }

  /**
   * Additional fields that are needed in order to complete the additional screening. The additional fields can be included as name value pairs (Field name, Field value)
   * @return additionalData
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<RecipientAdditionalDataInner> getAdditionalData() {
    return additionalData;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalData(List<RecipientAdditionalDataInner> additionalData) {
    this.additionalData = additionalData;
  }


  public PayoutWalletRequestRecipientDetail contactNumberType(ContactNumberTypeEnum contactNumberType) {
    this.contactNumberType = contactNumberType;
    return this;
  }

  /**
   * Get contactNumberType
   * @return contactNumberType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTACT_NUMBER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ContactNumberTypeEnum getContactNumberType() {
    return contactNumberType;
  }


  @JsonProperty(JSON_PROPERTY_CONTACT_NUMBER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContactNumberType(ContactNumberTypeEnum contactNumberType) {
    this.contactNumberType = contactNumberType;
  }


  public PayoutWalletRequestRecipientDetail identificationList(PayoutAccountRequestRecipientDetailIdentificationList identificationList) {
    this.identificationList = identificationList;
    return this;
  }

  /**
   * Get identificationList
   * @return identificationList
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFICATION_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PayoutAccountRequestRecipientDetailIdentificationList getIdentificationList() {
    return identificationList;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFICATION_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentificationList(PayoutAccountRequestRecipientDetailIdentificationList identificationList) {
    this.identificationList = identificationList;
  }


  public PayoutWalletRequestRecipientDetail name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Recipient company name. &lt;br&gt;Must not contain all numeric characters  ISO20022 field name: Creditor Name 
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public PayoutWalletRequestRecipientDetail type(Type type) {
    this.type = type;
    return this;
  }

  /**
   * Identifies the type of recipient - \&quot;C\&quot; for Company  
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Type getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(Type type) {
    this.type = type;
  }


  public PayoutWalletRequestRecipientDetail address(RecipientAccountPayoutAddress address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RecipientAccountPayoutAddress getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(RecipientAccountPayoutAddress address) {
    this.address = address;
  }


  public PayoutWalletRequestRecipientDetail lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * Recipient last name, conditionally required when name is not provided&lt;br&gt;Must not contain exclusively numeric characters&lt;br&gt;No special symbols &lt;table&gt;  &lt;tr&gt;  &lt;td&gt;!&lt;/td&gt;  &lt;td&gt;\&quot;&lt;/td&gt;  &lt;td&gt;£&lt;/td&gt;  &lt;td&gt;$&lt;/td&gt;  &lt;td&gt;%&lt;/td&gt;  &lt;td&gt;^&lt;/td&gt;  &lt;td&gt;*&lt;/td&gt;  &lt;td&gt;+&lt;/td&gt;  &lt;td&gt;&#x3D;&lt;/td&gt;  &lt;td&gt;¬&lt;/td&gt;  &lt;td&gt;¦&lt;/td&gt;  &lt;td&gt;:&lt;/td&gt;  &lt;td&gt;;&lt;/td&gt;  &lt;td&gt;@&lt;/td&gt;  &lt;td&gt;~&lt;/td&gt;  &lt;/tr&gt;  &lt;/table&gt;  ISO20022 field name: Creditor Name 
   * @return lastName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLastName() {
    return lastName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public PayoutWalletRequestRecipientDetail firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Recipient first name, conditionally required when name is not provided&lt;br&gt;Must not contain exclusively numeric characters&lt;br&gt;No special symbols &lt;table&gt;  &lt;tr&gt;  &lt;td&gt;!&lt;/td&gt;  &lt;td&gt;\&quot;&lt;/td&gt;  &lt;td&gt;£&lt;/td&gt;  &lt;td&gt;$&lt;/td&gt;  &lt;td&gt;%&lt;/td&gt;  &lt;td&gt;^&lt;/td&gt;  &lt;td&gt;*&lt;/td&gt;  &lt;td&gt;+&lt;/td&gt;  &lt;td&gt;&#x3D;&lt;/td&gt;  &lt;td&gt;¬&lt;/td&gt;  &lt;td&gt;¦&lt;/td&gt;  &lt;td&gt;:&lt;/td&gt;  &lt;td&gt;;&lt;/td&gt;  &lt;td&gt;@&lt;/td&gt;  &lt;td&gt;~&lt;/td&gt;  &lt;/tr&gt;  &lt;/table&gt;  ISO20022 field name: Creditor Name 
   * @return firstName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public PayoutWalletRequestRecipientDetail cityOfBirth(String cityOfBirth) {
    this.cityOfBirth = cityOfBirth;
    return this;
  }

  /**
   * Recipient city of birth  ISO20022 field name: Creditor City of Birth 
   * @return cityOfBirth
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY_OF_BIRTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCityOfBirth() {
    return cityOfBirth;
  }


  @JsonProperty(JSON_PROPERTY_CITY_OF_BIRTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCityOfBirth(String cityOfBirth) {
    this.cityOfBirth = cityOfBirth;
  }


  public PayoutWalletRequestRecipientDetail dateOfBirth(LocalDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

  /**
   * Recipient date of birth (Format: \&quot;YYYY-MM-DD\&quot;, e.g. \&quot;1980-02-01\&quot;)  Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths)  ISO20022 field name: Creditor Birth Date 
   * @return dateOfBirth
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_OF_BIRTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LocalDate getDateOfBirth() {
    return dateOfBirth;
  }


  @JsonProperty(JSON_PROPERTY_DATE_OF_BIRTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateOfBirth(LocalDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }


  public PayoutWalletRequestRecipientDetail countryOfBirth(String countryOfBirth) {
    this.countryOfBirth = countryOfBirth;
    return this;
  }

  /**
   * Recipient country of birth  Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths)  Format: 3-character ISO-3166 (Alpha-3) country code  ISO20022 field name: Creditor Country of Birth 
   * @return countryOfBirth
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY_OF_BIRTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCountryOfBirth() {
    return countryOfBirth;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_OF_BIRTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountryOfBirth(String countryOfBirth) {
    this.countryOfBirth = countryOfBirth;
  }


  /**
   * Return true if this PayoutWalletRequest_recipientDetail object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayoutWalletRequestRecipientDetail payoutWalletRequestRecipientDetail = (PayoutWalletRequestRecipientDetail) o;
    return Objects.equals(this.wallet, payoutWalletRequestRecipientDetail.wallet) &&
        Objects.equals(this.contactEmail, payoutWalletRequestRecipientDetail.contactEmail) &&
        Objects.equals(this.contactNumber, payoutWalletRequestRecipientDetail.contactNumber) &&
        Objects.equals(this.additionalData, payoutWalletRequestRecipientDetail.additionalData) &&
        Objects.equals(this.contactNumberType, payoutWalletRequestRecipientDetail.contactNumberType) &&
        Objects.equals(this.identificationList, payoutWalletRequestRecipientDetail.identificationList) &&
        Objects.equals(this.name, payoutWalletRequestRecipientDetail.name) &&
        Objects.equals(this.type, payoutWalletRequestRecipientDetail.type) &&
        Objects.equals(this.address, payoutWalletRequestRecipientDetail.address) &&
        Objects.equals(this.lastName, payoutWalletRequestRecipientDetail.lastName) &&
        Objects.equals(this.firstName, payoutWalletRequestRecipientDetail.firstName) &&
        Objects.equals(this.cityOfBirth, payoutWalletRequestRecipientDetail.cityOfBirth) &&
        Objects.equals(this.dateOfBirth, payoutWalletRequestRecipientDetail.dateOfBirth) &&
        Objects.equals(this.countryOfBirth, payoutWalletRequestRecipientDetail.countryOfBirth);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wallet, contactEmail, contactNumber, additionalData, contactNumberType, identificationList, name, type, address, lastName, firstName, cityOfBirth, dateOfBirth, countryOfBirth);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayoutWalletRequestRecipientDetail {\n");
    sb.append("    wallet: ").append(toIndentedString(wallet)).append("\n");
    sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
    sb.append("    contactNumber: ").append(toIndentedString(contactNumber)).append("\n");
    sb.append("    additionalData: ").append(toIndentedString(additionalData)).append("\n");
    sb.append("    contactNumberType: ").append(toIndentedString(contactNumberType)).append("\n");
    sb.append("    identificationList: ").append(toIndentedString(identificationList)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    cityOfBirth: ").append(toIndentedString(cityOfBirth)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    countryOfBirth: ").append(toIndentedString(countryOfBirth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `address` to the URL query string
    if (getAddress() != null) {
      joiner.add(getAddress().toUrlQueryString(prefix + "address" + suffix));
    }

    // add `lastName` to the URL query string
    if (getLastName() != null) {
      joiner.add(String.format("%slastName%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getLastName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `firstName` to the URL query string
    if (getFirstName() != null) {
      joiner.add(String.format("%sfirstName%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFirstName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `cityOfBirth` to the URL query string
    if (getCityOfBirth() != null) {
      joiner.add(String.format("%scityOfBirth%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCityOfBirth()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `dateOfBirth` to the URL query string
    if (getDateOfBirth() != null) {
      joiner.add(String.format("%sdateOfBirth%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDateOfBirth()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `countryOfBirth` to the URL query string
    if (getCountryOfBirth() != null) {
      joiner.add(String.format("%scountryOfBirth%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCountryOfBirth()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

