/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * QueryPayoutIdResponse200TransactionDetailTokenData
 */
@JsonPropertyOrder({
  QueryPayoutIdResponse200TransactionDetailTokenData.JSON_PROPERTY_ACCOUNT_RANGE,
  QueryPayoutIdResponse200TransactionDetailTokenData.JSON_PROPERTY_ACCOUNT_SUFFIX,
  QueryPayoutIdResponse200TransactionDetailTokenData.JSON_PROPERTY_ADDITIONAL_TOKEN_RESP_INFO
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class QueryPayoutIdResponse200TransactionDetailTokenData {
  public static final String JSON_PROPERTY_ACCOUNT_RANGE = "accountRange";
  private Integer accountRange;

  public static final String JSON_PROPERTY_ACCOUNT_SUFFIX = "accountSuffix";
  private String accountSuffix;

  public static final String JSON_PROPERTY_ADDITIONAL_TOKEN_RESP_INFO = "additionalTokenRespInfo";
  private String additionalTokenRespInfo;

  public QueryPayoutIdResponse200TransactionDetailTokenData() { 
  }

  public QueryPayoutIdResponse200TransactionDetailTokenData accountRange(Integer accountRange) {
    this.accountRange = accountRange;
    return this;
  }

  /**
   * Contains the first 9 digits of the cardholder PAN.. Note: Acquirers must not forward this value to their merchants after receiving it in the response message from Visa.  ISO20022 field name: N/A P2A: N/A P2W: N/A P2C: Optional
   * @return accountRange
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getAccountRange() {
    return accountRange;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountRange(Integer accountRange) {
    this.accountRange = accountRange;
  }


  public QueryPayoutIdResponse200TransactionDetailTokenData accountSuffix(String accountSuffix) {
    this.accountSuffix = accountSuffix;
    return this;
  }

  /**
   * Last four digits of the card number/PAN  Note: This is only relevant for push to card payouts, where a card network token was sent by the Originating Entity in the payout request (in the recipientDetail.card.accountNumber field).  ISO20022 field name: n/a P2A: N/A P2W: N/A P2C: Optional
   * @return accountSuffix
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_SUFFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAccountSuffix() {
    return accountSuffix;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_SUFFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountSuffix(String accountSuffix) {
    this.accountSuffix = accountSuffix;
  }


  public QueryPayoutIdResponse200TransactionDetailTokenData additionalTokenRespInfo(String additionalTokenRespInfo) {
    this.additionalTokenRespInfo = additionalTokenRespInfo;
    return this;
  }

  /**
   * This field will contain a value used to identify transactions eligible for token services.  Valid value:  1 - Token program.  ISO20022 field name: N/A P2A: N/A P2W: N/A P2C: Optional
   * @return additionalTokenRespInfo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_TOKEN_RESP_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAdditionalTokenRespInfo() {
    return additionalTokenRespInfo;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_TOKEN_RESP_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalTokenRespInfo(String additionalTokenRespInfo) {
    this.additionalTokenRespInfo = additionalTokenRespInfo;
  }


  /**
   * Return true if this QueryPayoutIdResponse200_transactionDetail_tokenData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryPayoutIdResponse200TransactionDetailTokenData queryPayoutIdResponse200TransactionDetailTokenData = (QueryPayoutIdResponse200TransactionDetailTokenData) o;
    return Objects.equals(this.accountRange, queryPayoutIdResponse200TransactionDetailTokenData.accountRange) &&
        Objects.equals(this.accountSuffix, queryPayoutIdResponse200TransactionDetailTokenData.accountSuffix) &&
        Objects.equals(this.additionalTokenRespInfo, queryPayoutIdResponse200TransactionDetailTokenData.additionalTokenRespInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountRange, accountSuffix, additionalTokenRespInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryPayoutIdResponse200TransactionDetailTokenData {\n");
    sb.append("    accountRange: ").append(toIndentedString(accountRange)).append("\n");
    sb.append("    accountSuffix: ").append(toIndentedString(accountSuffix)).append("\n");
    sb.append("    additionalTokenRespInfo: ").append(toIndentedString(additionalTokenRespInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `accountRange` to the URL query string
    if (getAccountRange() != null) {
      joiner.add(String.format("%saccountRange%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAccountRange()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `accountSuffix` to the URL query string
    if (getAccountSuffix() != null) {
      joiner.add(String.format("%saccountSuffix%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAccountSuffix()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `additionalTokenRespInfo` to the URL query string
    if (getAdditionalTokenRespInfo() != null) {
      joiner.add(String.format("%sadditionalTokenRespInfo%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAdditionalTokenRespInfo()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

