/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.RecipientAccountPayoutAddress2;
import com.example.transformation.dto.visa.RecipientCompany1;
import com.example.transformation.dto.visa.RecipientIndividual1;
import com.example.transformation.dto.visa.Type;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.example.transformation.dto.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
@JsonDeserialize(using = RecipientTransactorDetail1.RecipientTransactorDetail1Deserializer.class)
@JsonSerialize(using = RecipientTransactorDetail1.RecipientTransactorDetail1Serializer.class)
public class RecipientTransactorDetail1 extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(RecipientTransactorDetail1.class.getName());

    public static class RecipientTransactorDetail1Serializer extends StdSerializer<RecipientTransactorDetail1> {
        public RecipientTransactorDetail1Serializer(Class<RecipientTransactorDetail1> t) {
            super(t);
        }

        public RecipientTransactorDetail1Serializer() {
            this(null);
        }

        @Override
        public void serialize(RecipientTransactorDetail1 value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class RecipientTransactorDetail1Deserializer extends StdDeserializer<RecipientTransactorDetail1> {
        public RecipientTransactorDetail1Deserializer() {
            this(RecipientTransactorDetail1.class);
        }

        public RecipientTransactorDetail1Deserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public RecipientTransactorDetail1 deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize RecipientCompany1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (RecipientCompany1.class.equals(Integer.class) || RecipientCompany1.class.equals(Long.class) || RecipientCompany1.class.equals(Float.class) || RecipientCompany1.class.equals(Double.class) || RecipientCompany1.class.equals(Boolean.class) || RecipientCompany1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((RecipientCompany1.class.equals(Integer.class) || RecipientCompany1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((RecipientCompany1.class.equals(Float.class) || RecipientCompany1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (RecipientCompany1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (RecipientCompany1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(RecipientCompany1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'RecipientCompany1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'RecipientCompany1'", e);
            }

            // deserialize RecipientIndividual1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (RecipientIndividual1.class.equals(Integer.class) || RecipientIndividual1.class.equals(Long.class) || RecipientIndividual1.class.equals(Float.class) || RecipientIndividual1.class.equals(Double.class) || RecipientIndividual1.class.equals(Boolean.class) || RecipientIndividual1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((RecipientIndividual1.class.equals(Integer.class) || RecipientIndividual1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((RecipientIndividual1.class.equals(Float.class) || RecipientIndividual1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (RecipientIndividual1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (RecipientIndividual1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(RecipientIndividual1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'RecipientIndividual1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'RecipientIndividual1'", e);
            }

            if (match == 1) {
                RecipientTransactorDetail1 ret = new RecipientTransactorDetail1();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for RecipientTransactorDetail1: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public RecipientTransactorDetail1 getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "RecipientTransactorDetail1 cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public RecipientTransactorDetail1() {
        super("oneOf", Boolean.FALSE);
    }

    public RecipientTransactorDetail1(RecipientCompany1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public RecipientTransactorDetail1(RecipientIndividual1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("RecipientCompany1", RecipientCompany1.class);
        schemas.put("RecipientIndividual1", RecipientIndividual1.class);
        JSON.registerDescendants(RecipientTransactorDetail1.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return RecipientTransactorDetail1.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * RecipientCompany1, RecipientIndividual1
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(RecipientCompany1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(RecipientIndividual1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be RecipientCompany1, RecipientIndividual1");
    }

    /**
     * Get the actual instance, which can be the following:
     * RecipientCompany1, RecipientIndividual1
     *
     * @return The actual instance (RecipientCompany1, RecipientIndividual1)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `RecipientCompany1`. If the actual instance is not `RecipientCompany1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RecipientCompany1`
     * @throws ClassCastException if the instance is not `RecipientCompany1`
     */
    public RecipientCompany1 getRecipientCompany1() throws ClassCastException {
        return (RecipientCompany1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `RecipientIndividual1`. If the actual instance is not `RecipientIndividual1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RecipientIndividual1`
     * @throws ClassCastException if the instance is not `RecipientIndividual1`
     */
    public RecipientIndividual1 getRecipientIndividual1() throws ClassCastException {
        return (RecipientIndividual1)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof RecipientIndividual1) {
        if (getActualInstance() != null) {
          joiner.add(((RecipientIndividual1)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof RecipientCompany1) {
        if (getActualInstance() != null) {
          joiner.add(((RecipientCompany1)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

