/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.IdType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * RecipientIdentificationList1Inner
 */
@JsonPropertyOrder({
  RecipientIdentificationList1Inner.JSON_PROPERTY_ID_TYPE,
  RecipientIdentificationList1Inner.JSON_PROPERTY_ID_NUMBER,
  RecipientIdentificationList1Inner.JSON_PROPERTY_ID_ISSUE_COUNTRY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class RecipientIdentificationList1Inner {
  public static final String JSON_PROPERTY_ID_TYPE = "idType";
  private IdType idType;

  public static final String JSON_PROPERTY_ID_NUMBER = "idNumber";
  private String idNumber;

  public static final String JSON_PROPERTY_ID_ISSUE_COUNTRY = "idIssueCountry";
  private String idIssueCountry;

  public RecipientIdentificationList1Inner() { 
  }

  public RecipientIdentificationList1Inner idType(IdType idType) {
    this.idType = idType;
    return this;
  }

  /**
   * Recipient identification type (issued by a government or similar authority) needs to be provided by Originating Entity along with the payment in certain markets.   Valid values :  * P- Passport  * D-Driving License  * N-National Id  * T-Tax Id  * L-Legal Entity Registration Number  * F-Foreign Id  Conditional (Refer to Visa Direct Endpoint Guide on country-specific required fields and lengths)  ISO20022 field name: \&quot;Creditor Private Identification Code\&quot; or \&quot;Creditor Organisation Identification Code\&quot; 
   * @return idType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public IdType getIdType() {
    return idType;
  }


  @JsonProperty(JSON_PROPERTY_ID_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdType(IdType idType) {
    this.idType = idType;
  }


  public RecipientIdentificationList1Inner idNumber(String idNumber) {
    this.idNumber = idNumber;
    return this;
  }

  /**
   * Recipient identification number (issued by a government or similar authority) needs to be provided by Originating Entity along with the payment in certain markets.   Conditional (Refer to Visa Direct Endpoint Guide on country-specific required fields and lengths)  ISO20022 field name: \&quot;Creditor Private Identification\&quot; or \&quot;Creditor Organisation Identification\&quot; 
   * @return idNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIdNumber() {
    return idNumber;
  }


  @JsonProperty(JSON_PROPERTY_ID_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdNumber(String idNumber) {
    this.idNumber = idNumber;
  }


  public RecipientIdentificationList1Inner idIssueCountry(String idIssueCountry) {
    this.idIssueCountry = idIssueCountry;
    return this;
  }

  /**
   * Recipient identification issuing country needs to be provided by Originating Entity along with the payment in certain markets.   Format: 3-character ISO (Alpha-3) country code  Conditional (Refer to Visa Direct Endpoint Guide on country-specific required fields and lengths)  ISO20022 field name: \&quot;Creditor Private Identification Issuer Country\&quot; or \&quot;Creditor Organisation Identification Issuer Country\&quot; 
   * @return idIssueCountry
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID_ISSUE_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIdIssueCountry() {
    return idIssueCountry;
  }


  @JsonProperty(JSON_PROPERTY_ID_ISSUE_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdIssueCountry(String idIssueCountry) {
    this.idIssueCountry = idIssueCountry;
  }


  /**
   * Return true if this RecipientIdentificationList_1_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecipientIdentificationList1Inner recipientIdentificationList1Inner = (RecipientIdentificationList1Inner) o;
    return Objects.equals(this.idType, recipientIdentificationList1Inner.idType) &&
        Objects.equals(this.idNumber, recipientIdentificationList1Inner.idNumber) &&
        Objects.equals(this.idIssueCountry, recipientIdentificationList1Inner.idIssueCountry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idType, idNumber, idIssueCountry);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecipientIdentificationList1Inner {\n");
    sb.append("    idType: ").append(toIndentedString(idType)).append("\n");
    sb.append("    idNumber: ").append(toIndentedString(idNumber)).append("\n");
    sb.append("    idIssueCountry: ").append(toIndentedString(idIssueCountry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `idType` to the URL query string
    if (getIdType() != null) {
      joiner.add(String.format("%sidType%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getIdType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `idNumber` to the URL query string
    if (getIdNumber() != null) {
      joiner.add(String.format("%sidNumber%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getIdNumber()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `idIssueCountry` to the URL query string
    if (getIdIssueCountry() != null) {
      joiner.add(String.format("%sidIssueCountry%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getIdIssueCountry()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

