/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.RequestBodyRecipientDetailPrepaidBalanceData;
import com.example.transformation.dto.visa.RequestBodyRecipientDetailVauData;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * RequestBodyRecipientDetail
 */
@JsonPropertyOrder({
  RequestBodyRecipientDetail.JSON_PROPERTY_VAU_DATA,
  RequestBodyRecipientDetail.JSON_PROPERTY_PREPAID_BALANCE_DATA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class RequestBodyRecipientDetail {
  public static final String JSON_PROPERTY_VAU_DATA = "vauData";
  private RequestBodyRecipientDetailVauData vauData;

  public static final String JSON_PROPERTY_PREPAID_BALANCE_DATA = "prepaidBalanceData";
  private RequestBodyRecipientDetailPrepaidBalanceData prepaidBalanceData;

  public RequestBodyRecipientDetail() { 
  }

  public RequestBodyRecipientDetail vauData(RequestBodyRecipientDetailVauData vauData) {
    this.vauData = vauData;
    return this;
  }

  /**
   * Get vauData
   * @return vauData
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAU_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RequestBodyRecipientDetailVauData getVauData() {
    return vauData;
  }


  @JsonProperty(JSON_PROPERTY_VAU_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVauData(RequestBodyRecipientDetailVauData vauData) {
    this.vauData = vauData;
  }


  public RequestBodyRecipientDetail prepaidBalanceData(RequestBodyRecipientDetailPrepaidBalanceData prepaidBalanceData) {
    this.prepaidBalanceData = prepaidBalanceData;
    return this;
  }

  /**
   * Get prepaidBalanceData
   * @return prepaidBalanceData
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREPAID_BALANCE_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RequestBodyRecipientDetailPrepaidBalanceData getPrepaidBalanceData() {
    return prepaidBalanceData;
  }


  @JsonProperty(JSON_PROPERTY_PREPAID_BALANCE_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrepaidBalanceData(RequestBodyRecipientDetailPrepaidBalanceData prepaidBalanceData) {
    this.prepaidBalanceData = prepaidBalanceData;
  }


  /**
   * Return true if this requestBody_recipientDetail object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestBodyRecipientDetail requestBodyRecipientDetail = (RequestBodyRecipientDetail) o;
    return Objects.equals(this.vauData, requestBodyRecipientDetail.vauData) &&
        Objects.equals(this.prepaidBalanceData, requestBodyRecipientDetail.prepaidBalanceData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vauData, prepaidBalanceData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestBodyRecipientDetail {\n");
    sb.append("    vauData: ").append(toIndentedString(vauData)).append("\n");
    sb.append("    prepaidBalanceData: ").append(toIndentedString(prepaidBalanceData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `vauData` to the URL query string
    if (getVauData() != null) {
      joiner.add(getVauData().toUrlQueryString(prefix + "vauData" + suffix));
    }

    // add `prepaidBalanceData` to the URL query string
    if (getPrepaidBalanceData() != null) {
      joiner.add(getPrepaidBalanceData().toUrlQueryString(prefix + "prepaidBalanceData" + suffix));
    }

    return joiner.toString();
  }
}

