/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.RecipientDetailMetadata1;
import com.example.transformation.dto.visa.TransactionDetailMetadata1;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * S2AMetaData1
 */
@JsonPropertyOrder({
  S2AMetaData1.JSON_PROPERTY_RECIPIENT_DETAIL,
  S2AMetaData1.JSON_PROPERTY_TRANSACTION_DETAIL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class S2AMetaData1 {
  public static final String JSON_PROPERTY_RECIPIENT_DETAIL = "recipientDetail";
  private RecipientDetailMetadata1 recipientDetail;

  public static final String JSON_PROPERTY_TRANSACTION_DETAIL = "transactionDetail";
  private TransactionDetailMetadata1 transactionDetail;

  public S2AMetaData1() { 
  }

  public S2AMetaData1 recipientDetail(RecipientDetailMetadata1 recipientDetail) {
    this.recipientDetail = recipientDetail;
    return this;
  }

  /**
   * Get recipientDetail
   * @return recipientDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RECIPIENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RecipientDetailMetadata1 getRecipientDetail() {
    return recipientDetail;
  }


  @JsonProperty(JSON_PROPERTY_RECIPIENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecipientDetail(RecipientDetailMetadata1 recipientDetail) {
    this.recipientDetail = recipientDetail;
  }


  public S2AMetaData1 transactionDetail(TransactionDetailMetadata1 transactionDetail) {
    this.transactionDetail = transactionDetail;
    return this;
  }

  /**
   * Get transactionDetail
   * @return transactionDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TransactionDetailMetadata1 getTransactionDetail() {
    return transactionDetail;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionDetail(TransactionDetailMetadata1 transactionDetail) {
    this.transactionDetail = transactionDetail;
  }


  /**
   * Return true if this S2AMetaData-1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    S2AMetaData1 s2AMetaData1 = (S2AMetaData1) o;
    return Objects.equals(this.recipientDetail, s2AMetaData1.recipientDetail) &&
        Objects.equals(this.transactionDetail, s2AMetaData1.transactionDetail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recipientDetail, transactionDetail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class S2AMetaData1 {\n");
    sb.append("    recipientDetail: ").append(toIndentedString(recipientDetail)).append("\n");
    sb.append("    transactionDetail: ").append(toIndentedString(transactionDetail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `recipientDetail` to the URL query string
    if (getRecipientDetail() != null) {
      joiner.add(getRecipientDetail().toUrlQueryString(prefix + "recipientDetail" + suffix));
    }

    // add `transactionDetail` to the URL query string
    if (getTransactionDetail() != null) {
      joiner.add(getTransactionDetail().toUrlQueryString(prefix + "transactionDetail" + suffix));
    }

    return joiner.toString();
  }
}

