/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.SendPayoutFromOriginatorRequestTransactionDetailAdditionalDataInner;
import com.example.transformation.dto.visa.SendPayoutFromOriginatorRequestTransactionDetailNationalNetData;
import com.example.transformation.dto.visa.SendPayoutFromOriginatorRequestTransactionDetailPurchaseIdentifier;
import com.example.transformation.dto.visa.SendPayoutFromOriginatorRequestTransactionDetailServiceProcessingType;
import com.example.transformation.dto.visa.SendPayoutFromOriginatorRequestTransactionDetailSettlement;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * SendPayoutFromOriginatorRequestTransactionDetail
 */
@JsonPropertyOrder({
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_SURCHARGE,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_END_TO_END_ID,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_SETTLEMENT,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_PAYOUT_SPEED,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_SECONDARY_ID,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_SOURCE_AMOUNT,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_ADDITIONAL_DATA,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_NATIONAL_NET_DATA,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_PURPOSE_OF_PAYMENT,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_CLIENT_REFERENCE_ID,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_MESSAGE_REASON_CODE,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_TRANSACTION_AMOUNT,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_PURCHASE_IDENTIFIER,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_SOURCE_CURRENCY_CODE,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_STATEMENT_NARRATIVE,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_FEE_PROGRAM_INDICATOR,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_BUSINESS_APPLICATION_ID,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_SERVICE_PROCESSING_TYPE,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_TRANSACTION_IDENTIFIER,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_SYSTEM_TRACE_AUDIT_NUMBER,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_TRANSACTION_CURRENCY_CODE,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_LOCAL_TRANSACTION_DATE_TIME,
  SendPayoutFromOriginatorRequestTransactionDetail.JSON_PROPERTY_RETRIEVAL_REFERENCE_NUMBER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class SendPayoutFromOriginatorRequestTransactionDetail {
  public static final String JSON_PROPERTY_SURCHARGE = "surcharge";
  private String surcharge;

  public static final String JSON_PROPERTY_END_TO_END_ID = "endToEndId";
  private String endToEndId;

  public static final String JSON_PROPERTY_SETTLEMENT = "settlement";
  private SendPayoutFromOriginatorRequestTransactionDetailSettlement settlement;

  /**
   * Originating Entity to indicate the desired payout speed for the payment. Currently supported value is \&quot;STANDARD\&quot;. This field will be enhanced in future to include additional speed options  ISO20022 field name: Instruction Priority P2C: N/A 
   */
  public enum PayoutSpeedEnum {
    STANDARD("STANDARD"),
    
    PREMIUM("PREMIUM");

    private String value;

    PayoutSpeedEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PayoutSpeedEnum fromValue(String value) {
      for (PayoutSpeedEnum b : PayoutSpeedEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PAYOUT_SPEED = "payoutSpeed";
  private PayoutSpeedEnum payoutSpeed;

  public static final String JSON_PROPERTY_SECONDARY_ID = "secondaryId";
  private String secondaryId;

  public static final String JSON_PROPERTY_SOURCE_AMOUNT = "sourceAmount";
  private Integer sourceAmount;

  public static final String JSON_PROPERTY_ADDITIONAL_DATA = "additionalData";
  private List<SendPayoutFromOriginatorRequestTransactionDetailAdditionalDataInner> additionalData = new ArrayList<>();

  public static final String JSON_PROPERTY_NATIONAL_NET_DATA = "nationalNetData";
  private SendPayoutFromOriginatorRequestTransactionDetailNationalNetData nationalNetData;

  public static final String JSON_PROPERTY_PURPOSE_OF_PAYMENT = "purposeOfPayment";
  private String purposeOfPayment;

  public static final String JSON_PROPERTY_CLIENT_REFERENCE_ID = "clientReferenceId";
  private String clientReferenceId;

  public static final String JSON_PROPERTY_MESSAGE_REASON_CODE = "messageReasonCode";
  private String messageReasonCode;

  public static final String JSON_PROPERTY_TRANSACTION_AMOUNT = "transactionAmount";
  private Integer transactionAmount;

  public static final String JSON_PROPERTY_PURCHASE_IDENTIFIER = "purchaseIdentifier";
  private SendPayoutFromOriginatorRequestTransactionDetailPurchaseIdentifier purchaseIdentifier;

  public static final String JSON_PROPERTY_SOURCE_CURRENCY_CODE = "sourceCurrencyCode";
  private String sourceCurrencyCode;

  public static final String JSON_PROPERTY_STATEMENT_NARRATIVE = "statementNarrative";
  private String statementNarrative;

  public static final String JSON_PROPERTY_FEE_PROGRAM_INDICATOR = "feeProgramIndicator";
  private String feeProgramIndicator;

  public static final String JSON_PROPERTY_BUSINESS_APPLICATION_ID = "businessApplicationId";
  private String businessApplicationId;

  public static final String JSON_PROPERTY_SERVICE_PROCESSING_TYPE = "serviceProcessingType";
  private SendPayoutFromOriginatorRequestTransactionDetailServiceProcessingType serviceProcessingType;

  public static final String JSON_PROPERTY_TRANSACTION_IDENTIFIER = "transactionIdentifier";
  private String transactionIdentifier;

  public static final String JSON_PROPERTY_SYSTEM_TRACE_AUDIT_NUMBER = "systemTraceAuditNumber";
  private String systemTraceAuditNumber;

  public static final String JSON_PROPERTY_TRANSACTION_CURRENCY_CODE = "transactionCurrencyCode";
  private String transactionCurrencyCode;

  public static final String JSON_PROPERTY_LOCAL_TRANSACTION_DATE_TIME = "localTransactionDateTime";
  private String localTransactionDateTime;

  public static final String JSON_PROPERTY_RETRIEVAL_REFERENCE_NUMBER = "retrievalReferenceNumber";
  private String retrievalReferenceNumber;

  public SendPayoutFromOriginatorRequestTransactionDetail() { 
  }

  public SendPayoutFromOriginatorRequestTransactionDetail surcharge(String surcharge) {
    this.surcharge = surcharge;
    return this;
  }

  /**
   * When present, this field contains the sender&#39;s surcharge as assessed by the Originating Entity. Values in this field must be included in the transactionAmount and should be in the same currency and format as defined in the transactionAmount field.  ISO20022 field name: N/A P2A: N/A P2W: N/A P2C: Optional  Note: The number of decimal places assumed for this field depends on the currency. Refer to SMS POS Visa &amp; Visa Electron Technical Specifications - Appendix E Country and Currency codes for P2C.  Example: Currency exponent for USD is 2. If the amount is $100.99, then this field should populate “10099”. If the amount is $100.00 then this field should populate “10000”. Currency exponent for JPY is 0. If the amount is JPY 10,000, then this field should populate “10000”.
   * @return surcharge
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SURCHARGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSurcharge() {
    return surcharge;
  }


  @JsonProperty(JSON_PROPERTY_SURCHARGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSurcharge(String surcharge) {
    this.surcharge = surcharge;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail endToEndId(String endToEndId) {
    this.endToEndId = endToEndId;
    return this;
  }

  /**
   * Identifier assigned by the Originating Entity&#39;s customer to uniquely identify the transaction  ISO20022 field name: Payment Identification - EndtoEnd Identification P2A: Optional P2W: Optional P2C: N/A
   * @return endToEndId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_TO_END_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEndToEndId() {
    return endToEndId;
  }


  @JsonProperty(JSON_PROPERTY_END_TO_END_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndToEndId(String endToEndId) {
    this.endToEndId = endToEndId;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail settlement(SendPayoutFromOriginatorRequestTransactionDetailSettlement settlement) {
    this.settlement = settlement;
    return this;
  }

  /**
   * Get settlement
   * @return settlement
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SETTLEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SendPayoutFromOriginatorRequestTransactionDetailSettlement getSettlement() {
    return settlement;
  }


  @JsonProperty(JSON_PROPERTY_SETTLEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSettlement(SendPayoutFromOriginatorRequestTransactionDetailSettlement settlement) {
    this.settlement = settlement;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail payoutSpeed(PayoutSpeedEnum payoutSpeed) {
    this.payoutSpeed = payoutSpeed;
    return this;
  }

  /**
   * Originating Entity to indicate the desired payout speed for the payment. Currently supported value is \&quot;STANDARD\&quot;. This field will be enhanced in future to include additional speed options  ISO20022 field name: Instruction Priority P2C: N/A 
   * @return payoutSpeed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYOUT_SPEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PayoutSpeedEnum getPayoutSpeed() {
    return payoutSpeed;
  }


  @JsonProperty(JSON_PROPERTY_PAYOUT_SPEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayoutSpeed(PayoutSpeedEnum payoutSpeed) {
    this.payoutSpeed = payoutSpeed;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail secondaryId(String secondaryId) {
    this.secondaryId = secondaryId;
    return this;
  }

  /**
   * secondaryId is used for C2B use case in the CEMEA region where payee initiates the OCT to the payer. The merchant or acquirer may use this field to obtain an Agreement Id in order to process the request.  ISO20022 field name: N/A P2A: N/A P2W: N/A P2C: Optional
   * @return secondaryId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECONDARY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSecondaryId() {
    return secondaryId;
  }


  @JsonProperty(JSON_PROPERTY_SECONDARY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecondaryId(String secondaryId) {
    this.secondaryId = secondaryId;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail sourceAmount(Integer sourceAmount) {
    this.sourceAmount = sourceAmount;
    return this;
  }

  /**
   * Source Amount is required in certain markets to identify the transaction amount entered in the sender&#39;s currency code prior to FX conversion by the originating entity.  ISO20022 field name: N/A P2A: N/A P2W: N/A P2C: Optional  Note: The number of decimal places assumed for this field depends on the currency. Refer to SMS POS Visa &amp; Visa Electron Technical Specifications - Appendix E Country and Currency codes for P2C.  Example: Currency exponent for USD is 2. If the amount is $100.99, then this field should populate “10099”. If the amount is $100.00 then this field should populate “10000”. Currency exponent for JPY is 0. If the amount is JPY 10,000, then this field should populate “10000”.
   * @return sourceAmount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getSourceAmount() {
    return sourceAmount;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceAmount(Integer sourceAmount) {
    this.sourceAmount = sourceAmount;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail additionalData(List<SendPayoutFromOriginatorRequestTransactionDetailAdditionalDataInner> additionalData) {
    this.additionalData = additionalData;
    return this;
  }

  public SendPayoutFromOriginatorRequestTransactionDetail addAdditionalDataItem(SendPayoutFromOriginatorRequestTransactionDetailAdditionalDataInner additionalDataItem) {
    if (this.additionalData == null) {
      this.additionalData = new ArrayList<>();
    }
    this.additionalData.add(additionalDataItem);
    return this;
  }

  /**
   * Additional fields that are needed in order to complete the additional screening. The additional fields can be included as name value pairs (Field name, Field value) P2A: Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths) P2W: Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths) P2C: N/A 
   * @return additionalData
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SendPayoutFromOriginatorRequestTransactionDetailAdditionalDataInner> getAdditionalData() {
    return additionalData;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalData(List<SendPayoutFromOriginatorRequestTransactionDetailAdditionalDataInner> additionalData) {
    this.additionalData = additionalData;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail nationalNetData(SendPayoutFromOriginatorRequestTransactionDetailNationalNetData nationalNetData) {
    this.nationalNetData = nationalNetData;
    return this;
  }

  /**
   * Get nationalNetData
   * @return nationalNetData
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NATIONAL_NET_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SendPayoutFromOriginatorRequestTransactionDetailNationalNetData getNationalNetData() {
    return nationalNetData;
  }


  @JsonProperty(JSON_PROPERTY_NATIONAL_NET_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNationalNetData(SendPayoutFromOriginatorRequestTransactionDetailNationalNetData nationalNetData) {
    this.nationalNetData = nationalNetData;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail purposeOfPayment(String purposeOfPayment) {
    this.purposeOfPayment = purposeOfPayment;
    return this;
  }

  /**
   * Purpose of payment is required in certain markets to clearly identify the purpose of the payment based on the standard values defined for respective market  ISO20022 field name: Purpose of Payment P2A: Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths) P2W: Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths) P2C: Optional
   * @return purposeOfPayment
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PURPOSE_OF_PAYMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPurposeOfPayment() {
    return purposeOfPayment;
  }


  @JsonProperty(JSON_PROPERTY_PURPOSE_OF_PAYMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPurposeOfPayment(String purposeOfPayment) {
    this.purposeOfPayment = purposeOfPayment;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail clientReferenceId(String clientReferenceId) {
    this.clientReferenceId = clientReferenceId;
    return this;
  }

  /**
   * Identifier assigned by the Originating Entity to uniquely identify the transaction  ISO20022 field name: Payment Identification - Transaction Identification P2A: Optional P2W: Optional P2C: N/A
   * @return clientReferenceId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIENT_REFERENCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getClientReferenceId() {
    return clientReferenceId;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_REFERENCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientReferenceId(String clientReferenceId) {
    this.clientReferenceId = clientReferenceId;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail messageReasonCode(String messageReasonCode) {
    this.messageReasonCode = messageReasonCode;
    return this;
  }

  /**
   * Contains codes that combined with some other fields such as the BAI (Business Application Id) identify some unique use cases. For Sales Tax rebates this field should be populated with the value 5120 (Value-added tax/Sales Tax) along with the businessApplicationId field set to the value &#39;FD&#39; which indicates this push funds transfer is being conducted in order to facilitate a sales tax refund.  ISO20022 field name: N/A P2A: N/A P2W: N/A P2C: Optional
   * @return messageReasonCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMessageReasonCode() {
    return messageReasonCode;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessageReasonCode(String messageReasonCode) {
    this.messageReasonCode = messageReasonCode;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail transactionAmount(Integer transactionAmount) {
    this.transactionAmount = transactionAmount;
    return this;
  }

  /**
   * The transaction amount to be paid out to the recipient bank account or card.  Expressed in the currency specified in transaction currency code.   ISO20022 field name:  Transaction Information And Status - Instructed Amount P2A: Mandatory  P2A: Mandatory  P2C: Mandatory  Note: The number of decimal places assumed for this field depends on the currency. Refer to the Payouts Endpoint Guide for P2A on country-specific currency minor units. Refer to SMS POS Visa &amp; Visa Electron Technical Specifications - Appendix E Country and Currency codes for P2C.  Example: Currency exponent for USD is 2. If the amount is $100.99, then this field should populate “10099”. If the amount is $100.00 then this field should populate “10000”. Currency exponent for JPY is 0. If the amount is JPY 10,000, then this field should populate “10000”.
   * @return transactionAmount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getTransactionAmount() {
    return transactionAmount;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionAmount(Integer transactionAmount) {
    this.transactionAmount = transactionAmount;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail purchaseIdentifier(SendPayoutFromOriginatorRequestTransactionDetailPurchaseIdentifier purchaseIdentifier) {
    this.purchaseIdentifier = purchaseIdentifier;
    return this;
  }

  /**
   * Get purchaseIdentifier
   * @return purchaseIdentifier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PURCHASE_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SendPayoutFromOriginatorRequestTransactionDetailPurchaseIdentifier getPurchaseIdentifier() {
    return purchaseIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_PURCHASE_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPurchaseIdentifier(SendPayoutFromOriginatorRequestTransactionDetailPurchaseIdentifier purchaseIdentifier) {
    this.purchaseIdentifier = purchaseIdentifier;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail sourceCurrencyCode(String sourceCurrencyCode) {
    this.sourceCurrencyCode = sourceCurrencyCode;
    return this;
  }

  /**
   * 3-character alpha or numeric currency code for currency of the sourceAmount field. Refer to ISO Codes for list of currency codes.  ISO20022 field name: N/A P2A: N/A P2W: N/A P2C: Optional
   * @return sourceCurrencyCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSourceCurrencyCode() {
    return sourceCurrencyCode;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceCurrencyCode(String sourceCurrencyCode) {
    this.sourceCurrencyCode = sourceCurrencyCode;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail statementNarrative(String statementNarrative) {
    this.statementNarrative = statementNarrative;
    return this;
  }

  /**
   * Originating Entity is advised to provide a narrative that helps the recipient clearly identify the sender and reason for the payment. Text will be displayed on the recipient’s statement when the payment gets posted to the recipient’s account (depends on recipient bank&#39;s process)  ISO20022 field name: Remittance Information Unstructured P2A: Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths) P2W: Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths) P2C: N/A
   * @return statementNarrative
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATEMENT_NARRATIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatementNarrative() {
    return statementNarrative;
  }


  @JsonProperty(JSON_PROPERTY_STATEMENT_NARRATIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatementNarrative(String statementNarrative) {
    this.statementNarrative = statementNarrative;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail feeProgramIndicator(String feeProgramIndicator) {
    this.feeProgramIndicator = feeProgramIndicator;
    return this;
  }

  /**
   * Contains the fee program indicator, which is used to assess the Interchange Fee Amount in certain scenarios  ISO20022 field name: n/a P2A: N/A P2W: N/A P2C: Optional
   * @return feeProgramIndicator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FEE_PROGRAM_INDICATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFeeProgramIndicator() {
    return feeProgramIndicator;
  }


  @JsonProperty(JSON_PROPERTY_FEE_PROGRAM_INDICATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeeProgramIndicator(String feeProgramIndicator) {
    this.feeProgramIndicator = feeProgramIndicator;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail businessApplicationId(String businessApplicationId) {
    this.businessApplicationId = businessApplicationId;
    return this;
  }

  /**
   * Business Application Identifier (BAI) identifies the type of program for which the payment is being sent, i.e. whether it is a funds disbursement, money transfer etc. It should be a valid value allowed by Visa and approved for the program during onboarding.&lt;br&gt;For R2P feature, businessApplicationId will carry a new BAI value \&quot;RP\&quot; or existing value \&quot;BP\&quot; for C2B domestic OCTs.  Valid BAI for Push to Accounts: - Money transfer: AA, PP;  - Non-money transfer: BB, FD, GD, GP, LO, MD, OG, PD, BP;   Valid BAI for Push to Cards: - Money transfer: AA, PP, BI, FT, WT;  - Non-money transfer: BB, BP, CP, FD, GD, GP, LO, MD, OG, PD, TU, RP;  ISO20022 field name: Payment Category Purpose P2A: Mandatory  P2W: Mandatory  P2C: Mandatory 
   * @return businessApplicationId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BUSINESS_APPLICATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBusinessApplicationId() {
    return businessApplicationId;
  }


  @JsonProperty(JSON_PROPERTY_BUSINESS_APPLICATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBusinessApplicationId(String businessApplicationId) {
    this.businessApplicationId = businessApplicationId;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail serviceProcessingType(SendPayoutFromOriginatorRequestTransactionDetailServiceProcessingType serviceProcessingType) {
    this.serviceProcessingType = serviceProcessingType;
    return this;
  }

  /**
   * Get serviceProcessingType
   * @return serviceProcessingType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE_PROCESSING_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SendPayoutFromOriginatorRequestTransactionDetailServiceProcessingType getServiceProcessingType() {
    return serviceProcessingType;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_PROCESSING_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceProcessingType(SendPayoutFromOriginatorRequestTransactionDetailServiceProcessingType serviceProcessingType) {
    this.serviceProcessingType = serviceProcessingType;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail transactionIdentifier(String transactionIdentifier) {
    this.transactionIdentifier = transactionIdentifier;
    return this;
  }

  /**
   * Visa-generated Transaction Identifier that is unique for each original authorization and financial request. The identifier links original messages to subsequent messages, such as those for exception item processing and clearing records. If an AFT has been previously sent, corresponding to the Push to Card transaction, this field must include the VisaNet transaction identifier returned in the AFT response.  ISO20022 field name: N/A P2A: N/A P2W: N/A P2C: Optional
   * @return transactionIdentifier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTransactionIdentifier() {
    return transactionIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionIdentifier(String transactionIdentifier) {
    this.transactionIdentifier = transactionIdentifier;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail systemTraceAuditNumber(String systemTraceAuditNumber) {
    this.systemTraceAuditNumber = systemTraceAuditNumber;
    return this;
  }

  /**
   * This field contains a number assigned by the Originating Entity that uniquely identifies a transaction and all message types. The trace number is one of the key data elements used to match a response to its request or to match a message to others for a given transaction set  ISO20022 field name: N/A 
   * @return systemTraceAuditNumber
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SYSTEM_TRACE_AUDIT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSystemTraceAuditNumber() {
    return systemTraceAuditNumber;
  }


  @JsonProperty(JSON_PROPERTY_SYSTEM_TRACE_AUDIT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSystemTraceAuditNumber(String systemTraceAuditNumber) {
    this.systemTraceAuditNumber = systemTraceAuditNumber;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail transactionCurrencyCode(String transactionCurrencyCode) {
    this.transactionCurrencyCode = transactionCurrencyCode;
    return this;
  }

  /**
   * The 3-digit ISO-4217 code in this field reflects the currency associated to the transaction amount  Format: 3-digit ISO-4217 (numeric) currency code  ISO20022 field name:  Transaction Information And Status - Instructed Amount Currency Code P2A: Mandatory  P2W: Mandatory  P2C: Mandatory
   * @return transactionCurrencyCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTransactionCurrencyCode() {
    return transactionCurrencyCode;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionCurrencyCode(String transactionCurrencyCode) {
    this.transactionCurrencyCode = transactionCurrencyCode;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail localTransactionDateTime(String localTransactionDateTime) {
    this.localTransactionDateTime = localTransactionDateTime;
    return this;
  }

  /**
   * The date and time when the transaction takes place, expressed in the local time of the Originating Entity request Format: YYYY-MM-DDThh:mm:ss  ISO20022 field name: Message Creation Date Time 
   * @return localTransactionDateTime
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOCAL_TRANSACTION_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLocalTransactionDateTime() {
    return localTransactionDateTime;
  }


  @JsonProperty(JSON_PROPERTY_LOCAL_TRANSACTION_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocalTransactionDateTime(String localTransactionDateTime) {
    this.localTransactionDateTime = localTransactionDateTime;
  }


  public SendPayoutFromOriginatorRequestTransactionDetail retrievalReferenceNumber(String retrievalReferenceNumber) {
    this.retrievalReferenceNumber = retrievalReferenceNumber;
    return this;
  }

  /**
   * This is a unique identifier generated by the Originating Entity for a transaction and its one of the key fields for matching a transaction with the subsequent messages with in the transaction set example Notification, Returns, Cancel, Exception management via VD Portal for P2A and Reversals, Chargeback, Response, Advice for P2C.  The format is recommended to be ydddhhnnnnnn yddd - The first four digits must be a valid Julian date format, where the first digit &#x3D; 0-9 (last digit of current year) and the next three digits &#x3D; 001-366 (number of the day in the year).  hh - can be the two digit hour in a 24 hour clock (00-23) during which the transaction is performed.  nnnnnn - can be the systemsTraceAuditNumber or any 6 digit number  ISO20022 field name: Transaction Information And Status - Original Instruction Identification P2A: Mandatory  P2W: Mandatory  P2C: Mandatory
   * @return retrievalReferenceNumber
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RETRIEVAL_REFERENCE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRetrievalReferenceNumber() {
    return retrievalReferenceNumber;
  }


  @JsonProperty(JSON_PROPERTY_RETRIEVAL_REFERENCE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRetrievalReferenceNumber(String retrievalReferenceNumber) {
    this.retrievalReferenceNumber = retrievalReferenceNumber;
  }


  /**
   * Return true if this SendPayoutFromOriginatorRequest_transactionDetail object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendPayoutFromOriginatorRequestTransactionDetail sendPayoutFromOriginatorRequestTransactionDetail = (SendPayoutFromOriginatorRequestTransactionDetail) o;
    return Objects.equals(this.surcharge, sendPayoutFromOriginatorRequestTransactionDetail.surcharge) &&
        Objects.equals(this.endToEndId, sendPayoutFromOriginatorRequestTransactionDetail.endToEndId) &&
        Objects.equals(this.settlement, sendPayoutFromOriginatorRequestTransactionDetail.settlement) &&
        Objects.equals(this.payoutSpeed, sendPayoutFromOriginatorRequestTransactionDetail.payoutSpeed) &&
        Objects.equals(this.secondaryId, sendPayoutFromOriginatorRequestTransactionDetail.secondaryId) &&
        Objects.equals(this.sourceAmount, sendPayoutFromOriginatorRequestTransactionDetail.sourceAmount) &&
        Objects.equals(this.additionalData, sendPayoutFromOriginatorRequestTransactionDetail.additionalData) &&
        Objects.equals(this.nationalNetData, sendPayoutFromOriginatorRequestTransactionDetail.nationalNetData) &&
        Objects.equals(this.purposeOfPayment, sendPayoutFromOriginatorRequestTransactionDetail.purposeOfPayment) &&
        Objects.equals(this.clientReferenceId, sendPayoutFromOriginatorRequestTransactionDetail.clientReferenceId) &&
        Objects.equals(this.messageReasonCode, sendPayoutFromOriginatorRequestTransactionDetail.messageReasonCode) &&
        Objects.equals(this.transactionAmount, sendPayoutFromOriginatorRequestTransactionDetail.transactionAmount) &&
        Objects.equals(this.purchaseIdentifier, sendPayoutFromOriginatorRequestTransactionDetail.purchaseIdentifier) &&
        Objects.equals(this.sourceCurrencyCode, sendPayoutFromOriginatorRequestTransactionDetail.sourceCurrencyCode) &&
        Objects.equals(this.statementNarrative, sendPayoutFromOriginatorRequestTransactionDetail.statementNarrative) &&
        Objects.equals(this.feeProgramIndicator, sendPayoutFromOriginatorRequestTransactionDetail.feeProgramIndicator) &&
        Objects.equals(this.businessApplicationId, sendPayoutFromOriginatorRequestTransactionDetail.businessApplicationId) &&
        Objects.equals(this.serviceProcessingType, sendPayoutFromOriginatorRequestTransactionDetail.serviceProcessingType) &&
        Objects.equals(this.transactionIdentifier, sendPayoutFromOriginatorRequestTransactionDetail.transactionIdentifier) &&
        Objects.equals(this.systemTraceAuditNumber, sendPayoutFromOriginatorRequestTransactionDetail.systemTraceAuditNumber) &&
        Objects.equals(this.transactionCurrencyCode, sendPayoutFromOriginatorRequestTransactionDetail.transactionCurrencyCode) &&
        Objects.equals(this.localTransactionDateTime, sendPayoutFromOriginatorRequestTransactionDetail.localTransactionDateTime) &&
        Objects.equals(this.retrievalReferenceNumber, sendPayoutFromOriginatorRequestTransactionDetail.retrievalReferenceNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(surcharge, endToEndId, settlement, payoutSpeed, secondaryId, sourceAmount, additionalData, nationalNetData, purposeOfPayment, clientReferenceId, messageReasonCode, transactionAmount, purchaseIdentifier, sourceCurrencyCode, statementNarrative, feeProgramIndicator, businessApplicationId, serviceProcessingType, transactionIdentifier, systemTraceAuditNumber, transactionCurrencyCode, localTransactionDateTime, retrievalReferenceNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendPayoutFromOriginatorRequestTransactionDetail {\n");
    sb.append("    surcharge: ").append(toIndentedString(surcharge)).append("\n");
    sb.append("    endToEndId: ").append(toIndentedString(endToEndId)).append("\n");
    sb.append("    settlement: ").append(toIndentedString(settlement)).append("\n");
    sb.append("    payoutSpeed: ").append(toIndentedString(payoutSpeed)).append("\n");
    sb.append("    secondaryId: ").append(toIndentedString(secondaryId)).append("\n");
    sb.append("    sourceAmount: ").append(toIndentedString(sourceAmount)).append("\n");
    sb.append("    additionalData: ").append(toIndentedString(additionalData)).append("\n");
    sb.append("    nationalNetData: ").append(toIndentedString(nationalNetData)).append("\n");
    sb.append("    purposeOfPayment: ").append(toIndentedString(purposeOfPayment)).append("\n");
    sb.append("    clientReferenceId: ").append(toIndentedString(clientReferenceId)).append("\n");
    sb.append("    messageReasonCode: ").append(toIndentedString(messageReasonCode)).append("\n");
    sb.append("    transactionAmount: ").append(toIndentedString(transactionAmount)).append("\n");
    sb.append("    purchaseIdentifier: ").append(toIndentedString(purchaseIdentifier)).append("\n");
    sb.append("    sourceCurrencyCode: ").append(toIndentedString(sourceCurrencyCode)).append("\n");
    sb.append("    statementNarrative: ").append(toIndentedString(statementNarrative)).append("\n");
    sb.append("    feeProgramIndicator: ").append(toIndentedString(feeProgramIndicator)).append("\n");
    sb.append("    businessApplicationId: ").append(toIndentedString(businessApplicationId)).append("\n");
    sb.append("    serviceProcessingType: ").append(toIndentedString(serviceProcessingType)).append("\n");
    sb.append("    transactionIdentifier: ").append(toIndentedString(transactionIdentifier)).append("\n");
    sb.append("    systemTraceAuditNumber: ").append(toIndentedString(systemTraceAuditNumber)).append("\n");
    sb.append("    transactionCurrencyCode: ").append(toIndentedString(transactionCurrencyCode)).append("\n");
    sb.append("    localTransactionDateTime: ").append(toIndentedString(localTransactionDateTime)).append("\n");
    sb.append("    retrievalReferenceNumber: ").append(toIndentedString(retrievalReferenceNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `surcharge` to the URL query string
    if (getSurcharge() != null) {
      joiner.add(String.format("%ssurcharge%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSurcharge()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `endToEndId` to the URL query string
    if (getEndToEndId() != null) {
      joiner.add(String.format("%sendToEndId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getEndToEndId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `settlement` to the URL query string
    if (getSettlement() != null) {
      joiner.add(getSettlement().toUrlQueryString(prefix + "settlement" + suffix));
    }

    // add `payoutSpeed` to the URL query string
    if (getPayoutSpeed() != null) {
      joiner.add(String.format("%spayoutSpeed%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPayoutSpeed()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `secondaryId` to the URL query string
    if (getSecondaryId() != null) {
      joiner.add(String.format("%ssecondaryId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSecondaryId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `sourceAmount` to the URL query string
    if (getSourceAmount() != null) {
      joiner.add(String.format("%ssourceAmount%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSourceAmount()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `additionalData` to the URL query string
    if (getAdditionalData() != null) {
      for (int i = 0; i < getAdditionalData().size(); i++) {
        if (getAdditionalData().get(i) != null) {
          joiner.add(getAdditionalData().get(i).toUrlQueryString(String.format("%sadditionalData%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `nationalNetData` to the URL query string
    if (getNationalNetData() != null) {
      joiner.add(getNationalNetData().toUrlQueryString(prefix + "nationalNetData" + suffix));
    }

    // add `purposeOfPayment` to the URL query string
    if (getPurposeOfPayment() != null) {
      joiner.add(String.format("%spurposeOfPayment%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPurposeOfPayment()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `clientReferenceId` to the URL query string
    if (getClientReferenceId() != null) {
      joiner.add(String.format("%sclientReferenceId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getClientReferenceId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `messageReasonCode` to the URL query string
    if (getMessageReasonCode() != null) {
      joiner.add(String.format("%smessageReasonCode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMessageReasonCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `transactionAmount` to the URL query string
    if (getTransactionAmount() != null) {
      joiner.add(String.format("%stransactionAmount%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTransactionAmount()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `purchaseIdentifier` to the URL query string
    if (getPurchaseIdentifier() != null) {
      joiner.add(getPurchaseIdentifier().toUrlQueryString(prefix + "purchaseIdentifier" + suffix));
    }

    // add `sourceCurrencyCode` to the URL query string
    if (getSourceCurrencyCode() != null) {
      joiner.add(String.format("%ssourceCurrencyCode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSourceCurrencyCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `statementNarrative` to the URL query string
    if (getStatementNarrative() != null) {
      joiner.add(String.format("%sstatementNarrative%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getStatementNarrative()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `feeProgramIndicator` to the URL query string
    if (getFeeProgramIndicator() != null) {
      joiner.add(String.format("%sfeeProgramIndicator%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFeeProgramIndicator()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `businessApplicationId` to the URL query string
    if (getBusinessApplicationId() != null) {
      joiner.add(String.format("%sbusinessApplicationId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getBusinessApplicationId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `serviceProcessingType` to the URL query string
    if (getServiceProcessingType() != null) {
      joiner.add(getServiceProcessingType().toUrlQueryString(prefix + "serviceProcessingType" + suffix));
    }

    // add `transactionIdentifier` to the URL query string
    if (getTransactionIdentifier() != null) {
      joiner.add(String.format("%stransactionIdentifier%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTransactionIdentifier()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `systemTraceAuditNumber` to the URL query string
    if (getSystemTraceAuditNumber() != null) {
      joiner.add(String.format("%ssystemTraceAuditNumber%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSystemTraceAuditNumber()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `transactionCurrencyCode` to the URL query string
    if (getTransactionCurrencyCode() != null) {
      joiner.add(String.format("%stransactionCurrencyCode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTransactionCurrencyCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `localTransactionDateTime` to the URL query string
    if (getLocalTransactionDateTime() != null) {
      joiner.add(String.format("%slocalTransactionDateTime%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getLocalTransactionDateTime()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `retrievalReferenceNumber` to the URL query string
    if (getRetrievalReferenceNumber() != null) {
      joiner.add(String.format("%sretrievalReferenceNumber%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRetrievalReferenceNumber()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

