/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.AccountPayoutRequest1;
import com.example.transformation.dto.visa.DigitalAssetPayoutRequest;
import com.example.transformation.dto.visa.DigitalAssetWalletTransactionDetail;
import com.example.transformation.dto.visa.PayoutDigitalAssetRequestAlteredRecipientDetail;
import com.example.transformation.dto.visa.PayoutDigitalAssetRequestAlteredSenderDetail;
import com.example.transformation.dto.visa.PayoutMethod1;
import com.example.transformation.dto.visa.WalletPayoutRequest1;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.example.transformation.dto.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
@JsonDeserialize(using = SendPayoutRequest1.SendPayoutRequest1Deserializer.class)
@JsonSerialize(using = SendPayoutRequest1.SendPayoutRequest1Serializer.class)
public class SendPayoutRequest1 extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(SendPayoutRequest1.class.getName());

    public static class SendPayoutRequest1Serializer extends StdSerializer<SendPayoutRequest1> {
        public SendPayoutRequest1Serializer(Class<SendPayoutRequest1> t) {
            super(t);
        }

        public SendPayoutRequest1Serializer() {
            this(null);
        }

        @Override
        public void serialize(SendPayoutRequest1 value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class SendPayoutRequest1Deserializer extends StdDeserializer<SendPayoutRequest1> {
        public SendPayoutRequest1Deserializer() {
            this(SendPayoutRequest1.class);
        }

        public SendPayoutRequest1Deserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public SendPayoutRequest1 deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize AccountPayoutRequest1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (AccountPayoutRequest1.class.equals(Integer.class) || AccountPayoutRequest1.class.equals(Long.class) || AccountPayoutRequest1.class.equals(Float.class) || AccountPayoutRequest1.class.equals(Double.class) || AccountPayoutRequest1.class.equals(Boolean.class) || AccountPayoutRequest1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((AccountPayoutRequest1.class.equals(Integer.class) || AccountPayoutRequest1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((AccountPayoutRequest1.class.equals(Float.class) || AccountPayoutRequest1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (AccountPayoutRequest1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (AccountPayoutRequest1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(AccountPayoutRequest1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'AccountPayoutRequest1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'AccountPayoutRequest1'", e);
            }

            // deserialize DigitalAssetPayoutRequest
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DigitalAssetPayoutRequest.class.equals(Integer.class) || DigitalAssetPayoutRequest.class.equals(Long.class) || DigitalAssetPayoutRequest.class.equals(Float.class) || DigitalAssetPayoutRequest.class.equals(Double.class) || DigitalAssetPayoutRequest.class.equals(Boolean.class) || DigitalAssetPayoutRequest.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DigitalAssetPayoutRequest.class.equals(Integer.class) || DigitalAssetPayoutRequest.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DigitalAssetPayoutRequest.class.equals(Float.class) || DigitalAssetPayoutRequest.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DigitalAssetPayoutRequest.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DigitalAssetPayoutRequest.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(DigitalAssetPayoutRequest.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DigitalAssetPayoutRequest'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DigitalAssetPayoutRequest'", e);
            }

            // deserialize WalletPayoutRequest1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (WalletPayoutRequest1.class.equals(Integer.class) || WalletPayoutRequest1.class.equals(Long.class) || WalletPayoutRequest1.class.equals(Float.class) || WalletPayoutRequest1.class.equals(Double.class) || WalletPayoutRequest1.class.equals(Boolean.class) || WalletPayoutRequest1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((WalletPayoutRequest1.class.equals(Integer.class) || WalletPayoutRequest1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((WalletPayoutRequest1.class.equals(Float.class) || WalletPayoutRequest1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (WalletPayoutRequest1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (WalletPayoutRequest1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(WalletPayoutRequest1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'WalletPayoutRequest1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'WalletPayoutRequest1'", e);
            }

            if (match == 1) {
                SendPayoutRequest1 ret = new SendPayoutRequest1();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for SendPayoutRequest1: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public SendPayoutRequest1 getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "SendPayoutRequest1 cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public SendPayoutRequest1() {
        super("oneOf", Boolean.FALSE);
    }

    public SendPayoutRequest1(AccountPayoutRequest1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public SendPayoutRequest1(DigitalAssetPayoutRequest o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public SendPayoutRequest1(WalletPayoutRequest1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("AccountPayoutRequest1", AccountPayoutRequest1.class);
        schemas.put("DigitalAssetPayoutRequest", DigitalAssetPayoutRequest.class);
        schemas.put("WalletPayoutRequest1", WalletPayoutRequest1.class);
        JSON.registerDescendants(SendPayoutRequest1.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return SendPayoutRequest1.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * AccountPayoutRequest1, DigitalAssetPayoutRequest, WalletPayoutRequest1
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(AccountPayoutRequest1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(DigitalAssetPayoutRequest.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(WalletPayoutRequest1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be AccountPayoutRequest1, DigitalAssetPayoutRequest, WalletPayoutRequest1");
    }

    /**
     * Get the actual instance, which can be the following:
     * AccountPayoutRequest1, DigitalAssetPayoutRequest, WalletPayoutRequest1
     *
     * @return The actual instance (AccountPayoutRequest1, DigitalAssetPayoutRequest, WalletPayoutRequest1)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `AccountPayoutRequest1`. If the actual instance is not `AccountPayoutRequest1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AccountPayoutRequest1`
     * @throws ClassCastException if the instance is not `AccountPayoutRequest1`
     */
    public AccountPayoutRequest1 getAccountPayoutRequest1() throws ClassCastException {
        return (AccountPayoutRequest1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DigitalAssetPayoutRequest`. If the actual instance is not `DigitalAssetPayoutRequest`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DigitalAssetPayoutRequest`
     * @throws ClassCastException if the instance is not `DigitalAssetPayoutRequest`
     */
    public DigitalAssetPayoutRequest getDigitalAssetPayoutRequest() throws ClassCastException {
        return (DigitalAssetPayoutRequest)super.getActualInstance();
    }

    /**
     * Get the actual instance of `WalletPayoutRequest1`. If the actual instance is not `WalletPayoutRequest1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `WalletPayoutRequest1`
     * @throws ClassCastException if the instance is not `WalletPayoutRequest1`
     */
    public WalletPayoutRequest1 getWalletPayoutRequest1() throws ClassCastException {
        return (WalletPayoutRequest1)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof AccountPayoutRequest1) {
        if (getActualInstance() != null) {
          joiner.add(((AccountPayoutRequest1)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof WalletPayoutRequest1) {
        if (getActualInstance() != null) {
          joiner.add(((WalletPayoutRequest1)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof DigitalAssetPayoutRequest) {
        if (getActualInstance() != null) {
          joiner.add(((DigitalAssetPayoutRequest)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

