/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * SendPayoutFromOriginatorRequestSenderDetailAddress
 */
@JsonPropertyOrder({
  SendPayoutFromOriginatorRequestSenderDetailAddress.JSON_PROPERTY_CITY,
  SendPayoutFromOriginatorRequestSenderDetailAddress.JSON_PROPERTY_STATE,
  SendPayoutFromOriginatorRequestSenderDetailAddress.JSON_PROPERTY_COUNTRY,
  SendPayoutFromOriginatorRequestSenderDetailAddress.JSON_PROPERTY_POSTAL_CODE,
  SendPayoutFromOriginatorRequestSenderDetailAddress.JSON_PROPERTY_ADDRESS_LINE1,
  SendPayoutFromOriginatorRequestSenderDetailAddress.JSON_PROPERTY_ADDRESS_LINE2
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class SendPayoutFromOriginatorRequestSenderDetailAddress {
  public static final String JSON_PROPERTY_CITY = "city";
  private String city;

  public static final String JSON_PROPERTY_STATE = "state";
  private String state;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private String country;

  public static final String JSON_PROPERTY_POSTAL_CODE = "postalCode";
  private String postalCode;

  public static final String JSON_PROPERTY_ADDRESS_LINE1 = "addressLine1";
  private String addressLine1;

  public static final String JSON_PROPERTY_ADDRESS_LINE2 = "addressLine2";
  private String addressLine2;

  public SendPayoutFromOriginatorRequestSenderDetailAddress() { 
  }

  public SendPayoutFromOriginatorRequestSenderDetailAddress city(String city) {
    this.city = city;
    return this;
  }

  /**
   * Sender address city  ISO20022 field name: Ultimate Debtor Address Town Name   P2A: Mandatory.  P2W: Mandatory.   P2C: Optional. The maximum length is 25.
   * @return city
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(String city) {
    this.city = city;
  }


  public SendPayoutFromOriginatorRequestSenderDetailAddress state(String state) {
    this.state = state;
    return this;
  }

  /**
   * Sender address state  ISO20022 field name: Ultimate Debtor Address Country Sub-division P2A: Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths) P2W: Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths) P2C: Conditional (Refer to OCT GIG on country-specific required fields) P2C: The maximum length is 2.
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(String state) {
    this.state = state;
  }


  public SendPayoutFromOriginatorRequestSenderDetailAddress country(String country) {
    this.country = country;
    return this;
  }

  /**
   * Sender address country Format: 3-digit ISO-3166 (numeric) country code  ISO20022 field name: Ultimate Debtor Address Country  P2A: Mandatory.  P2W: Mandatory.  P2C:Conditional (Refer to OCT GIG on country-specific required fields)
   * @return country
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(String country) {
    this.country = country;
  }


  public SendPayoutFromOriginatorRequestSenderDetailAddress postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

  /**
   * Sender address postal code  ISO20022 field name: Ultimate Debtor Address Postal Code P2A: The minLength length is 1.  P2W: The minLength length is 1.  P2C: The maximum length is 10.
   * @return postalCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPostalCode() {
    return postalCode;
  }


  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public SendPayoutFromOriginatorRequestSenderDetailAddress addressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
    return this;
  }

  /**
   * Sender address line 1  ISO20022 field name: Ultimate Debtor Address Line 1  P2A: Mandatory.  P2W: Mandatory.  P2C: Optional. The maximum length is 35
   * @return addressLine1
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAddressLine1() {
    return addressLine1;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }


  public SendPayoutFromOriginatorRequestSenderDetailAddress addressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
    return this;
  }

  /**
   * Sender address line 2  ISO20022 field name: Ultimate Debtor Address Line 2 P2C: N/A
   * @return addressLine2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAddressLine2() {
    return addressLine2;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
  }


  /**
   * Return true if this SendPayoutFromOriginatorRequest_senderDetail_address object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendPayoutFromOriginatorRequestSenderDetailAddress sendPayoutFromOriginatorRequestSenderDetailAddress = (SendPayoutFromOriginatorRequestSenderDetailAddress) o;
    return Objects.equals(this.city, sendPayoutFromOriginatorRequestSenderDetailAddress.city) &&
        Objects.equals(this.state, sendPayoutFromOriginatorRequestSenderDetailAddress.state) &&
        Objects.equals(this.country, sendPayoutFromOriginatorRequestSenderDetailAddress.country) &&
        Objects.equals(this.postalCode, sendPayoutFromOriginatorRequestSenderDetailAddress.postalCode) &&
        Objects.equals(this.addressLine1, sendPayoutFromOriginatorRequestSenderDetailAddress.addressLine1) &&
        Objects.equals(this.addressLine2, sendPayoutFromOriginatorRequestSenderDetailAddress.addressLine2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, state, country, postalCode, addressLine1, addressLine2);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendPayoutFromOriginatorRequestSenderDetailAddress {\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `city` to the URL query string
    if (getCity() != null) {
      joiner.add(String.format("%scity%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCity()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `state` to the URL query string
    if (getState() != null) {
      joiner.add(String.format("%sstate%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getState()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `country` to the URL query string
    if (getCountry() != null) {
      joiner.add(String.format("%scountry%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCountry()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `postalCode` to the URL query string
    if (getPostalCode() != null) {
      joiner.add(String.format("%spostalCode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPostalCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `addressLine1` to the URL query string
    if (getAddressLine1() != null) {
      joiner.add(String.format("%saddressLine1%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAddressLine1()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `addressLine2` to the URL query string
    if (getAddressLine2() != null) {
      joiner.add(String.format("%saddressLine2%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAddressLine2()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

