/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.ValidatePayoutFromOriginatorRequestOriginatorDetailAddress;
import com.example.transformation.dto.visa.ValidatePayoutFromOriginatorRequestOriginatorDetailPaymentFacilitator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * ValidatePayoutFromOriginatorRequestOriginatorDetail
 */
@JsonPropertyOrder({
  ValidatePayoutFromOriginatorRequestOriginatorDetail.JSON_PROPERTY_BANK_ID,
  ValidatePayoutFromOriginatorRequestOriginatorDetail.JSON_PROPERTY_ADDRESS,
  ValidatePayoutFromOriginatorRequestOriginatorDetail.JSON_PROPERTY_BANK_B_I_C,
  ValidatePayoutFromOriginatorRequestOriginatorDetail.JSON_PROPERTY_ORIGINATOR_ID,
  ValidatePayoutFromOriginatorRequestOriginatorDetail.JSON_PROPERTY_ORIGINATOR_B_I_C,
  ValidatePayoutFromOriginatorRequestOriginatorDetail.JSON_PROPERTY_ORIGINATOR_NAME,
  ValidatePayoutFromOriginatorRequestOriginatorDetail.JSON_PROPERTY_PAYMENT_FACILITATOR,
  ValidatePayoutFromOriginatorRequestOriginatorDetail.JSON_PROPERTY_MERCHANT_CATEGORY_CODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class ValidatePayoutFromOriginatorRequestOriginatorDetail {
  public static final String JSON_PROPERTY_BANK_ID = "bankId";
  private Integer bankId;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private ValidatePayoutFromOriginatorRequestOriginatorDetailAddress address;

  public static final String JSON_PROPERTY_BANK_B_I_C = "bankBIC";
  private String bankBIC;

  public static final String JSON_PROPERTY_ORIGINATOR_ID = "originatorId";
  private String originatorId;

  public static final String JSON_PROPERTY_ORIGINATOR_B_I_C = "originatorBIC";
  private String originatorBIC;

  public static final String JSON_PROPERTY_ORIGINATOR_NAME = "originatorName";
  private String originatorName;

  public static final String JSON_PROPERTY_PAYMENT_FACILITATOR = "paymentFacilitator";
  private ValidatePayoutFromOriginatorRequestOriginatorDetailPaymentFacilitator paymentFacilitator;

  public static final String JSON_PROPERTY_MERCHANT_CATEGORY_CODE = "merchantCategoryCode";
  private String merchantCategoryCode;

  public ValidatePayoutFromOriginatorRequestOriginatorDetail() { 
  }

  public ValidatePayoutFromOriginatorRequestOriginatorDetail bankId(Integer bankId) {
    this.bankId = bankId;
    return this;
  }

  /**
   * Originating bank ID is the Bank Identification Number (BIN) assigned to each Visa Member upon enrollment. If the Originator is not a Financial Institution (FI) and will be processing using a sponsor FI (i.e. Acquirer ) , this is the BIN of the sponsoring FI (Acquirer). It uniquely identifies the Bank/FI that is sponsoring the Originating Entity in Visa’s core system. Note: This is also referred to as the “Acquiring BIN” by Visa  ISO20022 field name: Debtor Agent FI Identification  
   * @return bankId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BANK_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getBankId() {
    return bankId;
  }


  @JsonProperty(JSON_PROPERTY_BANK_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBankId(Integer bankId) {
    this.bankId = bankId;
  }


  public ValidatePayoutFromOriginatorRequestOriginatorDetail address(ValidatePayoutFromOriginatorRequestOriginatorDetailAddress address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ValidatePayoutFromOriginatorRequestOriginatorDetailAddress getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(ValidatePayoutFromOriginatorRequestOriginatorDetailAddress address) {
    this.address = address;
  }


  public ValidatePayoutFromOriginatorRequestOriginatorDetail bankBIC(String bankBIC) {
    this.bankBIC = bankBIC;
    return this;
  }

  /**
   * Business Identifier Code (BIC) of the Sponsor FI (Acquirer) ISO20022 field name: Debtor Agent FI BIC 
   * @return bankBIC
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BANK_B_I_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBankBIC() {
    return bankBIC;
  }


  @JsonProperty(JSON_PROPERTY_BANK_B_I_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBankBIC(String bankBIC) {
    this.bankBIC = bankBIC;
  }


  public ValidatePayoutFromOriginatorRequestOriginatorDetail originatorId(String originatorId) {
    this.originatorId = originatorId;
    return this;
  }

  /**
   * An alphanumeric field that uniquely identifies the Originating Entity for Push to Account transactions. The Originating Entity should populate Card Acceptor Terminal ID (CAID)  for Push to Card transactions.  ISO20022 field name: Debtor - Originating Entity Identification 
   * @return originatorId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORIGINATOR_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getOriginatorId() {
    return originatorId;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINATOR_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOriginatorId(String originatorId) {
    this.originatorId = originatorId;
  }


  public ValidatePayoutFromOriginatorRequestOriginatorDetail originatorBIC(String originatorBIC) {
    this.originatorBIC = originatorBIC;
    return this;
  }

  /**
   * Business Identifier Code (BIC) of the Originating entity ISO20022 field name: Debtor BIC Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths).
   * @return originatorBIC
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORIGINATOR_B_I_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOriginatorBIC() {
    return originatorBIC;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINATOR_B_I_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOriginatorBIC(String originatorBIC) {
    this.originatorBIC = originatorBIC;
  }


  public ValidatePayoutFromOriginatorRequestOriginatorDetail originatorName(String originatorName) {
    this.originatorName = originatorName;
    return this;
  }

  /**
   * The legal name of the merchant or originating entity sending the payment instruction to Visa. ISO20022 field name: Debtor Name
   * @return originatorName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORIGINATOR_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getOriginatorName() {
    return originatorName;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINATOR_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOriginatorName(String originatorName) {
    this.originatorName = originatorName;
  }


  public ValidatePayoutFromOriginatorRequestOriginatorDetail paymentFacilitator(ValidatePayoutFromOriginatorRequestOriginatorDetailPaymentFacilitator paymentFacilitator) {
    this.paymentFacilitator = paymentFacilitator;
    return this;
  }

  /**
   * Get paymentFacilitator
   * @return paymentFacilitator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_FACILITATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ValidatePayoutFromOriginatorRequestOriginatorDetailPaymentFacilitator getPaymentFacilitator() {
    return paymentFacilitator;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_FACILITATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentFacilitator(ValidatePayoutFromOriginatorRequestOriginatorDetailPaymentFacilitator paymentFacilitator) {
    this.paymentFacilitator = paymentFacilitator;
  }


  public ValidatePayoutFromOriginatorRequestOriginatorDetail merchantCategoryCode(String merchantCategoryCode) {
    this.merchantCategoryCode = merchantCategoryCode;
    return this;
  }

  /**
   * Code describing the merchant&#39;s type of business product or service known as the merchant category code (MCC). Codes are listed in the Visa Core Rules and Visa Product and Service Rules. ISO20022 field name: Debtor Other Identification 
   * @return merchantCategoryCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMerchantCategoryCode() {
    return merchantCategoryCode;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantCategoryCode(String merchantCategoryCode) {
    this.merchantCategoryCode = merchantCategoryCode;
  }


  /**
   * Return true if this ValidatePayoutFromOriginatorRequest_originatorDetail object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidatePayoutFromOriginatorRequestOriginatorDetail validatePayoutFromOriginatorRequestOriginatorDetail = (ValidatePayoutFromOriginatorRequestOriginatorDetail) o;
    return Objects.equals(this.bankId, validatePayoutFromOriginatorRequestOriginatorDetail.bankId) &&
        Objects.equals(this.address, validatePayoutFromOriginatorRequestOriginatorDetail.address) &&
        Objects.equals(this.bankBIC, validatePayoutFromOriginatorRequestOriginatorDetail.bankBIC) &&
        Objects.equals(this.originatorId, validatePayoutFromOriginatorRequestOriginatorDetail.originatorId) &&
        Objects.equals(this.originatorBIC, validatePayoutFromOriginatorRequestOriginatorDetail.originatorBIC) &&
        Objects.equals(this.originatorName, validatePayoutFromOriginatorRequestOriginatorDetail.originatorName) &&
        Objects.equals(this.paymentFacilitator, validatePayoutFromOriginatorRequestOriginatorDetail.paymentFacilitator) &&
        Objects.equals(this.merchantCategoryCode, validatePayoutFromOriginatorRequestOriginatorDetail.merchantCategoryCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankId, address, bankBIC, originatorId, originatorBIC, originatorName, paymentFacilitator, merchantCategoryCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidatePayoutFromOriginatorRequestOriginatorDetail {\n");
    sb.append("    bankId: ").append(toIndentedString(bankId)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    bankBIC: ").append(toIndentedString(bankBIC)).append("\n");
    sb.append("    originatorId: ").append(toIndentedString(originatorId)).append("\n");
    sb.append("    originatorBIC: ").append(toIndentedString(originatorBIC)).append("\n");
    sb.append("    originatorName: ").append(toIndentedString(originatorName)).append("\n");
    sb.append("    paymentFacilitator: ").append(toIndentedString(paymentFacilitator)).append("\n");
    sb.append("    merchantCategoryCode: ").append(toIndentedString(merchantCategoryCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `bankId` to the URL query string
    if (getBankId() != null) {
      joiner.add(String.format("%sbankId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getBankId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `address` to the URL query string
    if (getAddress() != null) {
      joiner.add(getAddress().toUrlQueryString(prefix + "address" + suffix));
    }

    // add `bankBIC` to the URL query string
    if (getBankBIC() != null) {
      joiner.add(String.format("%sbankBIC%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getBankBIC()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `originatorId` to the URL query string
    if (getOriginatorId() != null) {
      joiner.add(String.format("%soriginatorId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getOriginatorId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `originatorBIC` to the URL query string
    if (getOriginatorBIC() != null) {
      joiner.add(String.format("%soriginatorBIC%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getOriginatorBIC()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `originatorName` to the URL query string
    if (getOriginatorName() != null) {
      joiner.add(String.format("%soriginatorName%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getOriginatorName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `paymentFacilitator` to the URL query string
    if (getPaymentFacilitator() != null) {
      joiner.add(getPaymentFacilitator().toUrlQueryString(prefix + "paymentFacilitator" + suffix));
    }

    // add `merchantCategoryCode` to the URL query string
    if (getMerchantCategoryCode() != null) {
      joiner.add(String.format("%smerchantCategoryCode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMerchantCategoryCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

