/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.ValidatePayoutFromOriginatorRequestOriginatorDetail;
import com.example.transformation.dto.visa.ValidatePayoutFromOriginatorRequestRecipientDetail;
import com.example.transformation.dto.visa.ValidatePayoutFromOriginatorRequestSenderDetail;
import com.example.transformation.dto.visa.ValidatePayoutFromOriginatorRequestTransactionDetail;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * ValidatePayoutFromOriginatorRequest
 */
@JsonPropertyOrder({
  ValidatePayoutFromOriginatorRequest.JSON_PROPERTY_SENDER_DETAIL,
  ValidatePayoutFromOriginatorRequest.JSON_PROPERTY_RECIPIENT_DETAIL,
  ValidatePayoutFromOriginatorRequest.JSON_PROPERTY_ORIGINATOR_DETAIL,
  ValidatePayoutFromOriginatorRequest.JSON_PROPERTY_TRANSACTION_DETAIL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class ValidatePayoutFromOriginatorRequest {
  public static final String JSON_PROPERTY_SENDER_DETAIL = "senderDetail";
  private ValidatePayoutFromOriginatorRequestSenderDetail senderDetail;

  public static final String JSON_PROPERTY_RECIPIENT_DETAIL = "recipientDetail";
  private ValidatePayoutFromOriginatorRequestRecipientDetail recipientDetail;

  public static final String JSON_PROPERTY_ORIGINATOR_DETAIL = "originatorDetail";
  private ValidatePayoutFromOriginatorRequestOriginatorDetail originatorDetail;

  public static final String JSON_PROPERTY_TRANSACTION_DETAIL = "transactionDetail";
  private ValidatePayoutFromOriginatorRequestTransactionDetail transactionDetail;

  public ValidatePayoutFromOriginatorRequest() { 
  }

  public ValidatePayoutFromOriginatorRequest senderDetail(ValidatePayoutFromOriginatorRequestSenderDetail senderDetail) {
    this.senderDetail = senderDetail;
    return this;
  }

  /**
   * Get senderDetail
   * @return senderDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SENDER_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ValidatePayoutFromOriginatorRequestSenderDetail getSenderDetail() {
    return senderDetail;
  }


  @JsonProperty(JSON_PROPERTY_SENDER_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSenderDetail(ValidatePayoutFromOriginatorRequestSenderDetail senderDetail) {
    this.senderDetail = senderDetail;
  }


  public ValidatePayoutFromOriginatorRequest recipientDetail(ValidatePayoutFromOriginatorRequestRecipientDetail recipientDetail) {
    this.recipientDetail = recipientDetail;
    return this;
  }

  /**
   * Get recipientDetail
   * @return recipientDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RECIPIENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ValidatePayoutFromOriginatorRequestRecipientDetail getRecipientDetail() {
    return recipientDetail;
  }


  @JsonProperty(JSON_PROPERTY_RECIPIENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecipientDetail(ValidatePayoutFromOriginatorRequestRecipientDetail recipientDetail) {
    this.recipientDetail = recipientDetail;
  }


  public ValidatePayoutFromOriginatorRequest originatorDetail(ValidatePayoutFromOriginatorRequestOriginatorDetail originatorDetail) {
    this.originatorDetail = originatorDetail;
    return this;
  }

  /**
   * Get originatorDetail
   * @return originatorDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORIGINATOR_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ValidatePayoutFromOriginatorRequestOriginatorDetail getOriginatorDetail() {
    return originatorDetail;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINATOR_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOriginatorDetail(ValidatePayoutFromOriginatorRequestOriginatorDetail originatorDetail) {
    this.originatorDetail = originatorDetail;
  }


  public ValidatePayoutFromOriginatorRequest transactionDetail(ValidatePayoutFromOriginatorRequestTransactionDetail transactionDetail) {
    this.transactionDetail = transactionDetail;
    return this;
  }

  /**
   * Get transactionDetail
   * @return transactionDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ValidatePayoutFromOriginatorRequestTransactionDetail getTransactionDetail() {
    return transactionDetail;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionDetail(ValidatePayoutFromOriginatorRequestTransactionDetail transactionDetail) {
    this.transactionDetail = transactionDetail;
  }


  /**
   * Return true if this ValidatePayoutFromOriginatorRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidatePayoutFromOriginatorRequest validatePayoutFromOriginatorRequest = (ValidatePayoutFromOriginatorRequest) o;
    return Objects.equals(this.senderDetail, validatePayoutFromOriginatorRequest.senderDetail) &&
        Objects.equals(this.recipientDetail, validatePayoutFromOriginatorRequest.recipientDetail) &&
        Objects.equals(this.originatorDetail, validatePayoutFromOriginatorRequest.originatorDetail) &&
        Objects.equals(this.transactionDetail, validatePayoutFromOriginatorRequest.transactionDetail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(senderDetail, recipientDetail, originatorDetail, transactionDetail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidatePayoutFromOriginatorRequest {\n");
    sb.append("    senderDetail: ").append(toIndentedString(senderDetail)).append("\n");
    sb.append("    recipientDetail: ").append(toIndentedString(recipientDetail)).append("\n");
    sb.append("    originatorDetail: ").append(toIndentedString(originatorDetail)).append("\n");
    sb.append("    transactionDetail: ").append(toIndentedString(transactionDetail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `senderDetail` to the URL query string
    if (getSenderDetail() != null) {
      joiner.add(getSenderDetail().toUrlQueryString(prefix + "senderDetail" + suffix));
    }

    // add `recipientDetail` to the URL query string
    if (getRecipientDetail() != null) {
      joiner.add(getRecipientDetail().toUrlQueryString(prefix + "recipientDetail" + suffix));
    }

    // add `originatorDetail` to the URL query string
    if (getOriginatorDetail() != null) {
      joiner.add(getOriginatorDetail().toUrlQueryString(prefix + "originatorDetail" + suffix));
    }

    // add `transactionDetail` to the URL query string
    if (getTransactionDetail() != null) {
      joiner.add(getTransactionDetail().toUrlQueryString(prefix + "transactionDetail" + suffix));
    }

    return joiner.toString();
  }
}

