/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * ValidatePayoutFromOriginatorRequestRecipientDetailAddress
 */
@JsonPropertyOrder({
  ValidatePayoutFromOriginatorRequestRecipientDetailAddress.JSON_PROPERTY_CITY,
  ValidatePayoutFromOriginatorRequestRecipientDetailAddress.JSON_PROPERTY_STATE,
  ValidatePayoutFromOriginatorRequestRecipientDetailAddress.JSON_PROPERTY_COUNTRY,
  ValidatePayoutFromOriginatorRequestRecipientDetailAddress.JSON_PROPERTY_POSTAL_CODE,
  ValidatePayoutFromOriginatorRequestRecipientDetailAddress.JSON_PROPERTY_ADDRESS_LINE1,
  ValidatePayoutFromOriginatorRequestRecipientDetailAddress.JSON_PROPERTY_ADDRESS_LINE2
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class ValidatePayoutFromOriginatorRequestRecipientDetailAddress {
  public static final String JSON_PROPERTY_CITY = "city";
  private String city;

  public static final String JSON_PROPERTY_STATE = "state";
  private String state;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private String country;

  public static final String JSON_PROPERTY_POSTAL_CODE = "postalCode";
  private String postalCode;

  public static final String JSON_PROPERTY_ADDRESS_LINE1 = "addressLine1";
  private String addressLine1;

  public static final String JSON_PROPERTY_ADDRESS_LINE2 = "addressLine2";
  private String addressLine2;

  public ValidatePayoutFromOriginatorRequestRecipientDetailAddress() { 
  }

  public ValidatePayoutFromOriginatorRequestRecipientDetailAddress city(String city) {
    this.city = city;
    return this;
  }

  /**
   * RRecipient address city  ISO20022 field name: Creditor Address Town Name Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths)
   * @return city
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(String city) {
    this.city = city;
  }


  public ValidatePayoutFromOriginatorRequestRecipientDetailAddress state(String state) {
    this.state = state;
    return this;
  }

  /**
   * Recipient address state  ISO20022 field name: Creditor Address Country Sub-division Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths)
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(String state) {
    this.state = state;
  }


  public ValidatePayoutFromOriginatorRequestRecipientDetailAddress country(String country) {
    this.country = country;
    return this;
  }

  /**
   * Recipient address country Format: 3-digit ISO-3166 (numeric) country code  ISO20022 field name: Creditor Address Country Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths)
   * @return country
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(String country) {
    this.country = country;
  }


  public ValidatePayoutFromOriginatorRequestRecipientDetailAddress postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

  /**
   * Recipient address postal code  ISO20022 field name: Creditor Address Postal Code Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths)
   * @return postalCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPostalCode() {
    return postalCode;
  }


  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public ValidatePayoutFromOriginatorRequestRecipientDetailAddress addressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
    return this;
  }

  /**
   * Recipient address line 1  ISO20022 field name: Creditor Address Line 1 Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths)
   * @return addressLine1
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAddressLine1() {
    return addressLine1;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }


  public ValidatePayoutFromOriginatorRequestRecipientDetailAddress addressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
    return this;
  }

  /**
   * Recipient address line 2  ISO20022 field name: Creditor Address Line 2 Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths)
   * @return addressLine2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAddressLine2() {
    return addressLine2;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
  }


  /**
   * Return true if this ValidatePayoutFromOriginatorRequest_recipientDetail_address object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidatePayoutFromOriginatorRequestRecipientDetailAddress validatePayoutFromOriginatorRequestRecipientDetailAddress = (ValidatePayoutFromOriginatorRequestRecipientDetailAddress) o;
    return Objects.equals(this.city, validatePayoutFromOriginatorRequestRecipientDetailAddress.city) &&
        Objects.equals(this.state, validatePayoutFromOriginatorRequestRecipientDetailAddress.state) &&
        Objects.equals(this.country, validatePayoutFromOriginatorRequestRecipientDetailAddress.country) &&
        Objects.equals(this.postalCode, validatePayoutFromOriginatorRequestRecipientDetailAddress.postalCode) &&
        Objects.equals(this.addressLine1, validatePayoutFromOriginatorRequestRecipientDetailAddress.addressLine1) &&
        Objects.equals(this.addressLine2, validatePayoutFromOriginatorRequestRecipientDetailAddress.addressLine2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, state, country, postalCode, addressLine1, addressLine2);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidatePayoutFromOriginatorRequestRecipientDetailAddress {\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `city` to the URL query string
    if (getCity() != null) {
      joiner.add(String.format("%scity%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCity()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `state` to the URL query string
    if (getState() != null) {
      joiner.add(String.format("%sstate%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getState()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `country` to the URL query string
    if (getCountry() != null) {
      joiner.add(String.format("%scountry%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCountry()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `postalCode` to the URL query string
    if (getPostalCode() != null) {
      joiner.add(String.format("%spostalCode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPostalCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `addressLine1` to the URL query string
    if (getAddressLine1() != null) {
      joiner.add(String.format("%saddressLine1%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAddressLine1()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `addressLine2` to the URL query string
    if (getAddressLine2() != null) {
      joiner.add(String.format("%saddressLine2%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAddressLine2()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

