/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.AccountVerificationRequest4;
import com.example.transformation.dto.visa.AccountVerificationRequestRecipientDetail;
import com.example.transformation.dto.visa.VerifyRecipientWalletRequest4;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.example.transformation.dto.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
@JsonDeserialize(using = VerifyRecipientDetailRequest4.VerifyRecipientDetailRequest4Deserializer.class)
@JsonSerialize(using = VerifyRecipientDetailRequest4.VerifyRecipientDetailRequest4Serializer.class)
public class VerifyRecipientDetailRequest4 extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(VerifyRecipientDetailRequest4.class.getName());

    public static class VerifyRecipientDetailRequest4Serializer extends StdSerializer<VerifyRecipientDetailRequest4> {
        public VerifyRecipientDetailRequest4Serializer(Class<VerifyRecipientDetailRequest4> t) {
            super(t);
        }

        public VerifyRecipientDetailRequest4Serializer() {
            this(null);
        }

        @Override
        public void serialize(VerifyRecipientDetailRequest4 value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class VerifyRecipientDetailRequest4Deserializer extends StdDeserializer<VerifyRecipientDetailRequest4> {
        public VerifyRecipientDetailRequest4Deserializer() {
            this(VerifyRecipientDetailRequest4.class);
        }

        public VerifyRecipientDetailRequest4Deserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public VerifyRecipientDetailRequest4 deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize AccountVerificationRequest4
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (AccountVerificationRequest4.class.equals(Integer.class) || AccountVerificationRequest4.class.equals(Long.class) || AccountVerificationRequest4.class.equals(Float.class) || AccountVerificationRequest4.class.equals(Double.class) || AccountVerificationRequest4.class.equals(Boolean.class) || AccountVerificationRequest4.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((AccountVerificationRequest4.class.equals(Integer.class) || AccountVerificationRequest4.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((AccountVerificationRequest4.class.equals(Float.class) || AccountVerificationRequest4.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (AccountVerificationRequest4.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (AccountVerificationRequest4.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(AccountVerificationRequest4.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'AccountVerificationRequest4'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'AccountVerificationRequest4'", e);
            }

            // deserialize VerifyRecipientWalletRequest4
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (VerifyRecipientWalletRequest4.class.equals(Integer.class) || VerifyRecipientWalletRequest4.class.equals(Long.class) || VerifyRecipientWalletRequest4.class.equals(Float.class) || VerifyRecipientWalletRequest4.class.equals(Double.class) || VerifyRecipientWalletRequest4.class.equals(Boolean.class) || VerifyRecipientWalletRequest4.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((VerifyRecipientWalletRequest4.class.equals(Integer.class) || VerifyRecipientWalletRequest4.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((VerifyRecipientWalletRequest4.class.equals(Float.class) || VerifyRecipientWalletRequest4.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (VerifyRecipientWalletRequest4.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (VerifyRecipientWalletRequest4.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(VerifyRecipientWalletRequest4.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'VerifyRecipientWalletRequest4'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'VerifyRecipientWalletRequest4'", e);
            }

            if (match == 1) {
                VerifyRecipientDetailRequest4 ret = new VerifyRecipientDetailRequest4();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for VerifyRecipientDetailRequest4: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public VerifyRecipientDetailRequest4 getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "VerifyRecipientDetailRequest4 cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public VerifyRecipientDetailRequest4() {
        super("oneOf", Boolean.FALSE);
    }

    public VerifyRecipientDetailRequest4(AccountVerificationRequest4 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public VerifyRecipientDetailRequest4(VerifyRecipientWalletRequest4 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("AccountVerificationRequest4", AccountVerificationRequest4.class);
        schemas.put("VerifyRecipientWalletRequest4", VerifyRecipientWalletRequest4.class);
        JSON.registerDescendants(VerifyRecipientDetailRequest4.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return VerifyRecipientDetailRequest4.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * AccountVerificationRequest4, VerifyRecipientWalletRequest4
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(AccountVerificationRequest4.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(VerifyRecipientWalletRequest4.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be AccountVerificationRequest4, VerifyRecipientWalletRequest4");
    }

    /**
     * Get the actual instance, which can be the following:
     * AccountVerificationRequest4, VerifyRecipientWalletRequest4
     *
     * @return The actual instance (AccountVerificationRequest4, VerifyRecipientWalletRequest4)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `AccountVerificationRequest4`. If the actual instance is not `AccountVerificationRequest4`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AccountVerificationRequest4`
     * @throws ClassCastException if the instance is not `AccountVerificationRequest4`
     */
    public AccountVerificationRequest4 getAccountVerificationRequest4() throws ClassCastException {
        return (AccountVerificationRequest4)super.getActualInstance();
    }

    /**
     * Get the actual instance of `VerifyRecipientWalletRequest4`. If the actual instance is not `VerifyRecipientWalletRequest4`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `VerifyRecipientWalletRequest4`
     * @throws ClassCastException if the instance is not `VerifyRecipientWalletRequest4`
     */
    public VerifyRecipientWalletRequest4 getVerifyRecipientWalletRequest4() throws ClassCastException {
        return (VerifyRecipientWalletRequest4)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof VerifyRecipientWalletRequest4) {
        if (getActualInstance() != null) {
          joiner.add(((VerifyRecipientWalletRequest4)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof AccountVerificationRequest4) {
        if (getActualInstance() != null) {
          joiner.add(((AccountVerificationRequest4)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

