/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.AccountVerificationRequest2;
import com.example.transformation.dto.visa.VerifyRecipientDigitalAssetRequest;
import com.example.transformation.dto.visa.VerifyRecipientDigitalAssetRequestRecipientDetail;
import com.example.transformation.dto.visa.VerifyRecipientWalletRequest2;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.example.transformation.dto.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
@JsonDeserialize(using = VerifyRecipientDetailRequest2.VerifyRecipientDetailRequest2Deserializer.class)
@JsonSerialize(using = VerifyRecipientDetailRequest2.VerifyRecipientDetailRequest2Serializer.class)
public class VerifyRecipientDetailRequest2 extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(VerifyRecipientDetailRequest2.class.getName());

    public static class VerifyRecipientDetailRequest2Serializer extends StdSerializer<VerifyRecipientDetailRequest2> {
        public VerifyRecipientDetailRequest2Serializer(Class<VerifyRecipientDetailRequest2> t) {
            super(t);
        }

        public VerifyRecipientDetailRequest2Serializer() {
            this(null);
        }

        @Override
        public void serialize(VerifyRecipientDetailRequest2 value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class VerifyRecipientDetailRequest2Deserializer extends StdDeserializer<VerifyRecipientDetailRequest2> {
        public VerifyRecipientDetailRequest2Deserializer() {
            this(VerifyRecipientDetailRequest2.class);
        }

        public VerifyRecipientDetailRequest2Deserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public VerifyRecipientDetailRequest2 deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize AccountVerificationRequest2
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (AccountVerificationRequest2.class.equals(Integer.class) || AccountVerificationRequest2.class.equals(Long.class) || AccountVerificationRequest2.class.equals(Float.class) || AccountVerificationRequest2.class.equals(Double.class) || AccountVerificationRequest2.class.equals(Boolean.class) || AccountVerificationRequest2.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((AccountVerificationRequest2.class.equals(Integer.class) || AccountVerificationRequest2.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((AccountVerificationRequest2.class.equals(Float.class) || AccountVerificationRequest2.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (AccountVerificationRequest2.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (AccountVerificationRequest2.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(AccountVerificationRequest2.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'AccountVerificationRequest2'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'AccountVerificationRequest2'", e);
            }

            // deserialize VerifyRecipientDigitalAssetRequest
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (VerifyRecipientDigitalAssetRequest.class.equals(Integer.class) || VerifyRecipientDigitalAssetRequest.class.equals(Long.class) || VerifyRecipientDigitalAssetRequest.class.equals(Float.class) || VerifyRecipientDigitalAssetRequest.class.equals(Double.class) || VerifyRecipientDigitalAssetRequest.class.equals(Boolean.class) || VerifyRecipientDigitalAssetRequest.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((VerifyRecipientDigitalAssetRequest.class.equals(Integer.class) || VerifyRecipientDigitalAssetRequest.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((VerifyRecipientDigitalAssetRequest.class.equals(Float.class) || VerifyRecipientDigitalAssetRequest.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (VerifyRecipientDigitalAssetRequest.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (VerifyRecipientDigitalAssetRequest.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(VerifyRecipientDigitalAssetRequest.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'VerifyRecipientDigitalAssetRequest'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'VerifyRecipientDigitalAssetRequest'", e);
            }

            // deserialize VerifyRecipientWalletRequest2
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (VerifyRecipientWalletRequest2.class.equals(Integer.class) || VerifyRecipientWalletRequest2.class.equals(Long.class) || VerifyRecipientWalletRequest2.class.equals(Float.class) || VerifyRecipientWalletRequest2.class.equals(Double.class) || VerifyRecipientWalletRequest2.class.equals(Boolean.class) || VerifyRecipientWalletRequest2.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((VerifyRecipientWalletRequest2.class.equals(Integer.class) || VerifyRecipientWalletRequest2.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((VerifyRecipientWalletRequest2.class.equals(Float.class) || VerifyRecipientWalletRequest2.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (VerifyRecipientWalletRequest2.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (VerifyRecipientWalletRequest2.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(VerifyRecipientWalletRequest2.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'VerifyRecipientWalletRequest2'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'VerifyRecipientWalletRequest2'", e);
            }

            if (match == 1) {
                VerifyRecipientDetailRequest2 ret = new VerifyRecipientDetailRequest2();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for VerifyRecipientDetailRequest2: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public VerifyRecipientDetailRequest2 getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "VerifyRecipientDetailRequest2 cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public VerifyRecipientDetailRequest2() {
        super("oneOf", Boolean.FALSE);
    }

    public VerifyRecipientDetailRequest2(AccountVerificationRequest2 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public VerifyRecipientDetailRequest2(VerifyRecipientDigitalAssetRequest o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public VerifyRecipientDetailRequest2(VerifyRecipientWalletRequest2 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("AccountVerificationRequest2", AccountVerificationRequest2.class);
        schemas.put("VerifyRecipientDigitalAssetRequest", VerifyRecipientDigitalAssetRequest.class);
        schemas.put("VerifyRecipientWalletRequest2", VerifyRecipientWalletRequest2.class);
        JSON.registerDescendants(VerifyRecipientDetailRequest2.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return VerifyRecipientDetailRequest2.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * AccountVerificationRequest2, VerifyRecipientDigitalAssetRequest, VerifyRecipientWalletRequest2
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(AccountVerificationRequest2.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(VerifyRecipientDigitalAssetRequest.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(VerifyRecipientWalletRequest2.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be AccountVerificationRequest2, VerifyRecipientDigitalAssetRequest, VerifyRecipientWalletRequest2");
    }

    /**
     * Get the actual instance, which can be the following:
     * AccountVerificationRequest2, VerifyRecipientDigitalAssetRequest, VerifyRecipientWalletRequest2
     *
     * @return The actual instance (AccountVerificationRequest2, VerifyRecipientDigitalAssetRequest, VerifyRecipientWalletRequest2)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `AccountVerificationRequest2`. If the actual instance is not `AccountVerificationRequest2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AccountVerificationRequest2`
     * @throws ClassCastException if the instance is not `AccountVerificationRequest2`
     */
    public AccountVerificationRequest2 getAccountVerificationRequest2() throws ClassCastException {
        return (AccountVerificationRequest2)super.getActualInstance();
    }

    /**
     * Get the actual instance of `VerifyRecipientDigitalAssetRequest`. If the actual instance is not `VerifyRecipientDigitalAssetRequest`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `VerifyRecipientDigitalAssetRequest`
     * @throws ClassCastException if the instance is not `VerifyRecipientDigitalAssetRequest`
     */
    public VerifyRecipientDigitalAssetRequest getVerifyRecipientDigitalAssetRequest() throws ClassCastException {
        return (VerifyRecipientDigitalAssetRequest)super.getActualInstance();
    }

    /**
     * Get the actual instance of `VerifyRecipientWalletRequest2`. If the actual instance is not `VerifyRecipientWalletRequest2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `VerifyRecipientWalletRequest2`
     * @throws ClassCastException if the instance is not `VerifyRecipientWalletRequest2`
     */
    public VerifyRecipientWalletRequest2 getVerifyRecipientWalletRequest2() throws ClassCastException {
        return (VerifyRecipientWalletRequest2)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof VerifyRecipientWalletRequest2) {
        if (getActualInstance() != null) {
          joiner.add(((VerifyRecipientWalletRequest2)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof AccountVerificationRequest2) {
        if (getActualInstance() != null) {
          joiner.add(((AccountVerificationRequest2)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof VerifyRecipientDigitalAssetRequest) {
        if (getActualInstance() != null) {
          joiner.add(((VerifyRecipientDigitalAssetRequest)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

