/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.CompanyRecipientIdentificationListWalletInner;
import com.example.transformation.dto.visa.RecipientAccountPayoutAddress1;
import com.example.transformation.dto.visa.RecipientIsIndividual4;
import com.example.transformation.dto.visa.Type;
import com.example.transformation.dto.visa.WalletRecipientIsCompany4;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.example.transformation.dto.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
@JsonDeserialize(using = WalletRecipientTransactorDetailWithID4.WalletRecipientTransactorDetailWithID4Deserializer.class)
@JsonSerialize(using = WalletRecipientTransactorDetailWithID4.WalletRecipientTransactorDetailWithID4Serializer.class)
public class WalletRecipientTransactorDetailWithID4 extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(WalletRecipientTransactorDetailWithID4.class.getName());

    public static class WalletRecipientTransactorDetailWithID4Serializer extends StdSerializer<WalletRecipientTransactorDetailWithID4> {
        public WalletRecipientTransactorDetailWithID4Serializer(Class<WalletRecipientTransactorDetailWithID4> t) {
            super(t);
        }

        public WalletRecipientTransactorDetailWithID4Serializer() {
            this(null);
        }

        @Override
        public void serialize(WalletRecipientTransactorDetailWithID4 value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class WalletRecipientTransactorDetailWithID4Deserializer extends StdDeserializer<WalletRecipientTransactorDetailWithID4> {
        public WalletRecipientTransactorDetailWithID4Deserializer() {
            this(WalletRecipientTransactorDetailWithID4.class);
        }

        public WalletRecipientTransactorDetailWithID4Deserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public WalletRecipientTransactorDetailWithID4 deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize RecipientIsIndividual4
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (RecipientIsIndividual4.class.equals(Integer.class) || RecipientIsIndividual4.class.equals(Long.class) || RecipientIsIndividual4.class.equals(Float.class) || RecipientIsIndividual4.class.equals(Double.class) || RecipientIsIndividual4.class.equals(Boolean.class) || RecipientIsIndividual4.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((RecipientIsIndividual4.class.equals(Integer.class) || RecipientIsIndividual4.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((RecipientIsIndividual4.class.equals(Float.class) || RecipientIsIndividual4.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (RecipientIsIndividual4.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (RecipientIsIndividual4.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(RecipientIsIndividual4.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'RecipientIsIndividual4'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'RecipientIsIndividual4'", e);
            }

            // deserialize WalletRecipientIsCompany4
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (WalletRecipientIsCompany4.class.equals(Integer.class) || WalletRecipientIsCompany4.class.equals(Long.class) || WalletRecipientIsCompany4.class.equals(Float.class) || WalletRecipientIsCompany4.class.equals(Double.class) || WalletRecipientIsCompany4.class.equals(Boolean.class) || WalletRecipientIsCompany4.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((WalletRecipientIsCompany4.class.equals(Integer.class) || WalletRecipientIsCompany4.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((WalletRecipientIsCompany4.class.equals(Float.class) || WalletRecipientIsCompany4.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (WalletRecipientIsCompany4.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (WalletRecipientIsCompany4.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(WalletRecipientIsCompany4.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'WalletRecipientIsCompany4'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'WalletRecipientIsCompany4'", e);
            }

            if (match == 1) {
                WalletRecipientTransactorDetailWithID4 ret = new WalletRecipientTransactorDetailWithID4();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for WalletRecipientTransactorDetailWithID4: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public WalletRecipientTransactorDetailWithID4 getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "WalletRecipientTransactorDetailWithID4 cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public WalletRecipientTransactorDetailWithID4() {
        super("oneOf", Boolean.FALSE);
    }

    public WalletRecipientTransactorDetailWithID4(RecipientIsIndividual4 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public WalletRecipientTransactorDetailWithID4(WalletRecipientIsCompany4 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("RecipientIsIndividual4", RecipientIsIndividual4.class);
        schemas.put("WalletRecipientIsCompany4", WalletRecipientIsCompany4.class);
        JSON.registerDescendants(WalletRecipientTransactorDetailWithID4.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return WalletRecipientTransactorDetailWithID4.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * RecipientIsIndividual4, WalletRecipientIsCompany4
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(RecipientIsIndividual4.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(WalletRecipientIsCompany4.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be RecipientIsIndividual4, WalletRecipientIsCompany4");
    }

    /**
     * Get the actual instance, which can be the following:
     * RecipientIsIndividual4, WalletRecipientIsCompany4
     *
     * @return The actual instance (RecipientIsIndividual4, WalletRecipientIsCompany4)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `RecipientIsIndividual4`. If the actual instance is not `RecipientIsIndividual4`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RecipientIsIndividual4`
     * @throws ClassCastException if the instance is not `RecipientIsIndividual4`
     */
    public RecipientIsIndividual4 getRecipientIsIndividual4() throws ClassCastException {
        return (RecipientIsIndividual4)super.getActualInstance();
    }

    /**
     * Get the actual instance of `WalletRecipientIsCompany4`. If the actual instance is not `WalletRecipientIsCompany4`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `WalletRecipientIsCompany4`
     * @throws ClassCastException if the instance is not `WalletRecipientIsCompany4`
     */
    public WalletRecipientIsCompany4 getWalletRecipientIsCompany4() throws ClassCastException {
        return (WalletRecipientIsCompany4)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof RecipientIsIndividual4) {
        if (getActualInstance() != null) {
          joiner.add(((RecipientIsIndividual4)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof WalletRecipientIsCompany4) {
        if (getActualInstance() != null) {
          joiner.add(((WalletRecipientIsCompany4)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

