/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * AccountBalanceWithTimestamp
 */
@JsonPropertyOrder({
  AccountBalanceWithTimestamp.JSON_PROPERTY_ACCOUNT_ID,
  AccountBalanceWithTimestamp.JSON_PROPERTY_BALANCE_TIMESTAMP,
  AccountBalanceWithTimestamp.JSON_PROPERTY_LAST_TRANSACTION_TIMESTAMP
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class AccountBalanceWithTimestamp {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  private String accountId;

  public static final String JSON_PROPERTY_BALANCE_TIMESTAMP = "balanceTimestamp";
  private OffsetDateTime balanceTimestamp;

  public static final String JSON_PROPERTY_LAST_TRANSACTION_TIMESTAMP = "lastTransactionTimestamp";
  private OffsetDateTime lastTransactionTimestamp;

  public AccountBalanceWithTimestamp() { 
  }

  public AccountBalanceWithTimestamp accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * The accountId uniquely identifies the ledger account as a virtual account number(i.e. VAN), with a value or number assigned by Visa.
   * @return accountId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccountId() {
    return accountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }


  public AccountBalanceWithTimestamp balanceTimestamp(OffsetDateTime balanceTimestamp) {
    this.balanceTimestamp = balanceTimestamp;
    return this;
  }

  /**
   * ISO 8601 formatted UTC Timestamp, YYYY-MM-DDThh:mm:ss.sssTZD. TZD is either Z or +/-00:00  example: 2020-05-05T12:12:12.000Z, or 1997-07-16T19:20:30.45+00:00  ISO20022 field name: Transaction Information And Status - Message Creation Date Time 
   * @return balanceTimestamp
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BALANCE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getBalanceTimestamp() {
    return balanceTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_BALANCE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBalanceTimestamp(OffsetDateTime balanceTimestamp) {
    this.balanceTimestamp = balanceTimestamp;
  }


  public AccountBalanceWithTimestamp lastTransactionTimestamp(OffsetDateTime lastTransactionTimestamp) {
    this.lastTransactionTimestamp = lastTransactionTimestamp;
    return this;
  }

  /**
   * The timestamp of the last money movement on the client&#39;s account.   This is a valid ISO 8601 timestamp, such as YYYY-MM-DDThh:mm:ss.sss±hh:mm.                   
   * @return lastTransactionTimestamp
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_TRANSACTION_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getLastTransactionTimestamp() {
    return lastTransactionTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_LAST_TRANSACTION_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastTransactionTimestamp(OffsetDateTime lastTransactionTimestamp) {
    this.lastTransactionTimestamp = lastTransactionTimestamp;
  }


  /**
   * Return true if this AccountBalanceWithTimestamp object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountBalanceWithTimestamp accountBalanceWithTimestamp = (AccountBalanceWithTimestamp) o;
    return Objects.equals(this.accountId, accountBalanceWithTimestamp.accountId) &&
        Objects.equals(this.balanceTimestamp, accountBalanceWithTimestamp.balanceTimestamp) &&
        Objects.equals(this.lastTransactionTimestamp, accountBalanceWithTimestamp.lastTransactionTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, balanceTimestamp, lastTransactionTimestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountBalanceWithTimestamp {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    balanceTimestamp: ").append(toIndentedString(balanceTimestamp)).append("\n");
    sb.append("    lastTransactionTimestamp: ").append(toIndentedString(lastTransactionTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `accountId` to the URL query string
    if (getAccountId() != null) {
      joiner.add(String.format("%saccountId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAccountId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `balanceTimestamp` to the URL query string
    if (getBalanceTimestamp() != null) {
      joiner.add(String.format("%sbalanceTimestamp%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getBalanceTimestamp()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `lastTransactionTimestamp` to the URL query string
    if (getLastTransactionTimestamp() != null) {
      joiner.add(String.format("%slastTransactionTimestamp%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getLastTransactionTimestamp()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

