/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.AccountVerificationRequestRecipientDetail;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * AccountVerificationRequest4
 */
@JsonPropertyOrder({
  AccountVerificationRequest4.JSON_PROPERTY_PAYOUT_METHOD,
  AccountVerificationRequest4.JSON_PROPERTY_RECIPIENT_DETAIL,
  AccountVerificationRequest4.JSON_PROPERTY_INITIATING_PARTY_ID,
  AccountVerificationRequest4.JSON_PROPERTY_CLIENT_VERIFICATION_REFERENCE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class AccountVerificationRequest4 {
  /**
   * Method of payout. For accounts, this should be &#39;B&#39;.
   */
  public enum PayoutMethodEnum {
    B("B");

    private String value;

    PayoutMethodEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PayoutMethodEnum fromValue(String value) {
      for (PayoutMethodEnum b : PayoutMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PAYOUT_METHOD = "payoutMethod";
  private PayoutMethodEnum payoutMethod;

  public static final String JSON_PROPERTY_RECIPIENT_DETAIL = "recipientDetail";
  private AccountVerificationRequestRecipientDetail recipientDetail;

  public static final String JSON_PROPERTY_INITIATING_PARTY_ID = "initiatingPartyId";
  private String initiatingPartyId;

  public static final String JSON_PROPERTY_CLIENT_VERIFICATION_REFERENCE = "clientVerificationReference";
  private String clientVerificationReference;

  public AccountVerificationRequest4() { 
  }

  public AccountVerificationRequest4 payoutMethod(PayoutMethodEnum payoutMethod) {
    this.payoutMethod = payoutMethod;
    return this;
  }

  /**
   * Method of payout. For accounts, this should be &#39;B&#39;.
   * @return payoutMethod
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYOUT_METHOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PayoutMethodEnum getPayoutMethod() {
    return payoutMethod;
  }


  @JsonProperty(JSON_PROPERTY_PAYOUT_METHOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayoutMethod(PayoutMethodEnum payoutMethod) {
    this.payoutMethod = payoutMethod;
  }


  public AccountVerificationRequest4 recipientDetail(AccountVerificationRequestRecipientDetail recipientDetail) {
    this.recipientDetail = recipientDetail;
    return this;
  }

  /**
   * Get recipientDetail
   * @return recipientDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RECIPIENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AccountVerificationRequestRecipientDetail getRecipientDetail() {
    return recipientDetail;
  }


  @JsonProperty(JSON_PROPERTY_RECIPIENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecipientDetail(AccountVerificationRequestRecipientDetail recipientDetail) {
    this.recipientDetail = recipientDetail;
  }


  public AccountVerificationRequest4 initiatingPartyId(String initiatingPartyId) {
    this.initiatingPartyId = initiatingPartyId;
    return this;
  }

  /**
   * The ID of the initiating party.
   * @return initiatingPartyId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INITIATING_PARTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getInitiatingPartyId() {
    return initiatingPartyId;
  }


  @JsonProperty(JSON_PROPERTY_INITIATING_PARTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInitiatingPartyId(String initiatingPartyId) {
    this.initiatingPartyId = initiatingPartyId;
  }


  public AccountVerificationRequest4 clientVerificationReference(String clientVerificationReference) {
    this.clientVerificationReference = clientVerificationReference;
    return this;
  }

  /**
   * A client submitted identifier. This field and same value will be returned in the response.
   * @return clientVerificationReference
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLIENT_VERIFICATION_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getClientVerificationReference() {
    return clientVerificationReference;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_VERIFICATION_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientVerificationReference(String clientVerificationReference) {
    this.clientVerificationReference = clientVerificationReference;
  }


  /**
   * Return true if this AccountVerificationRequest-4 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountVerificationRequest4 accountVerificationRequest4 = (AccountVerificationRequest4) o;
    return Objects.equals(this.payoutMethod, accountVerificationRequest4.payoutMethod) &&
        Objects.equals(this.recipientDetail, accountVerificationRequest4.recipientDetail) &&
        Objects.equals(this.initiatingPartyId, accountVerificationRequest4.initiatingPartyId) &&
        Objects.equals(this.clientVerificationReference, accountVerificationRequest4.clientVerificationReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payoutMethod, recipientDetail, initiatingPartyId, clientVerificationReference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountVerificationRequest4 {\n");
    sb.append("    payoutMethod: ").append(toIndentedString(payoutMethod)).append("\n");
    sb.append("    recipientDetail: ").append(toIndentedString(recipientDetail)).append("\n");
    sb.append("    initiatingPartyId: ").append(toIndentedString(initiatingPartyId)).append("\n");
    sb.append("    clientVerificationReference: ").append(toIndentedString(clientVerificationReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `payoutMethod` to the URL query string
    if (getPayoutMethod() != null) {
      joiner.add(String.format("%spayoutMethod%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPayoutMethod()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `recipientDetail` to the URL query string
    if (getRecipientDetail() != null) {
      joiner.add(getRecipientDetail().toUrlQueryString(prefix + "recipientDetail" + suffix));
    }

    // add `initiatingPartyId` to the URL query string
    if (getInitiatingPartyId() != null) {
      joiner.add(String.format("%sinitiatingPartyId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getInitiatingPartyId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `clientVerificationReference` to the URL query string
    if (getClientVerificationReference() != null) {
      joiner.add(String.format("%sclientVerificationReference%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getClientVerificationReference()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

