/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.DigitalAssetCompanyRecipientIdentificationListWalletInner;
import com.example.transformation.dto.visa.DigitalAssetRecipientIsCompany;
import com.example.transformation.dto.visa.DigitalAssetRecipientIsIndividual;
import com.example.transformation.dto.visa.DigitalAssetRecipientPayoutAddress;
import com.example.transformation.dto.visa.Type;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.example.transformation.dto.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
@JsonDeserialize(using = DigitalAssetRecipientTransactorDetailWithID.DigitalAssetRecipientTransactorDetailWithIDDeserializer.class)
@JsonSerialize(using = DigitalAssetRecipientTransactorDetailWithID.DigitalAssetRecipientTransactorDetailWithIDSerializer.class)
public class DigitalAssetRecipientTransactorDetailWithID extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(DigitalAssetRecipientTransactorDetailWithID.class.getName());

    public static class DigitalAssetRecipientTransactorDetailWithIDSerializer extends StdSerializer<DigitalAssetRecipientTransactorDetailWithID> {
        public DigitalAssetRecipientTransactorDetailWithIDSerializer(Class<DigitalAssetRecipientTransactorDetailWithID> t) {
            super(t);
        }

        public DigitalAssetRecipientTransactorDetailWithIDSerializer() {
            this(null);
        }

        @Override
        public void serialize(DigitalAssetRecipientTransactorDetailWithID value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class DigitalAssetRecipientTransactorDetailWithIDDeserializer extends StdDeserializer<DigitalAssetRecipientTransactorDetailWithID> {
        public DigitalAssetRecipientTransactorDetailWithIDDeserializer() {
            this(DigitalAssetRecipientTransactorDetailWithID.class);
        }

        public DigitalAssetRecipientTransactorDetailWithIDDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public DigitalAssetRecipientTransactorDetailWithID deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize DigitalAssetRecipientIsCompany
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DigitalAssetRecipientIsCompany.class.equals(Integer.class) || DigitalAssetRecipientIsCompany.class.equals(Long.class) || DigitalAssetRecipientIsCompany.class.equals(Float.class) || DigitalAssetRecipientIsCompany.class.equals(Double.class) || DigitalAssetRecipientIsCompany.class.equals(Boolean.class) || DigitalAssetRecipientIsCompany.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DigitalAssetRecipientIsCompany.class.equals(Integer.class) || DigitalAssetRecipientIsCompany.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DigitalAssetRecipientIsCompany.class.equals(Float.class) || DigitalAssetRecipientIsCompany.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DigitalAssetRecipientIsCompany.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DigitalAssetRecipientIsCompany.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(DigitalAssetRecipientIsCompany.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DigitalAssetRecipientIsCompany'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DigitalAssetRecipientIsCompany'", e);
            }

            // deserialize DigitalAssetRecipientIsIndividual
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DigitalAssetRecipientIsIndividual.class.equals(Integer.class) || DigitalAssetRecipientIsIndividual.class.equals(Long.class) || DigitalAssetRecipientIsIndividual.class.equals(Float.class) || DigitalAssetRecipientIsIndividual.class.equals(Double.class) || DigitalAssetRecipientIsIndividual.class.equals(Boolean.class) || DigitalAssetRecipientIsIndividual.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DigitalAssetRecipientIsIndividual.class.equals(Integer.class) || DigitalAssetRecipientIsIndividual.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DigitalAssetRecipientIsIndividual.class.equals(Float.class) || DigitalAssetRecipientIsIndividual.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DigitalAssetRecipientIsIndividual.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DigitalAssetRecipientIsIndividual.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(DigitalAssetRecipientIsIndividual.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DigitalAssetRecipientIsIndividual'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DigitalAssetRecipientIsIndividual'", e);
            }

            if (match == 1) {
                DigitalAssetRecipientTransactorDetailWithID ret = new DigitalAssetRecipientTransactorDetailWithID();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for DigitalAssetRecipientTransactorDetailWithID: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public DigitalAssetRecipientTransactorDetailWithID getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "DigitalAssetRecipientTransactorDetailWithID cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public DigitalAssetRecipientTransactorDetailWithID() {
        super("oneOf", Boolean.FALSE);
    }

    public DigitalAssetRecipientTransactorDetailWithID(DigitalAssetRecipientIsCompany o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public DigitalAssetRecipientTransactorDetailWithID(DigitalAssetRecipientIsIndividual o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("DigitalAssetRecipientIsCompany", DigitalAssetRecipientIsCompany.class);
        schemas.put("DigitalAssetRecipientIsIndividual", DigitalAssetRecipientIsIndividual.class);
        JSON.registerDescendants(DigitalAssetRecipientTransactorDetailWithID.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return DigitalAssetRecipientTransactorDetailWithID.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * DigitalAssetRecipientIsCompany, DigitalAssetRecipientIsIndividual
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(DigitalAssetRecipientIsCompany.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(DigitalAssetRecipientIsIndividual.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be DigitalAssetRecipientIsCompany, DigitalAssetRecipientIsIndividual");
    }

    /**
     * Get the actual instance, which can be the following:
     * DigitalAssetRecipientIsCompany, DigitalAssetRecipientIsIndividual
     *
     * @return The actual instance (DigitalAssetRecipientIsCompany, DigitalAssetRecipientIsIndividual)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `DigitalAssetRecipientIsCompany`. If the actual instance is not `DigitalAssetRecipientIsCompany`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DigitalAssetRecipientIsCompany`
     * @throws ClassCastException if the instance is not `DigitalAssetRecipientIsCompany`
     */
    public DigitalAssetRecipientIsCompany getDigitalAssetRecipientIsCompany() throws ClassCastException {
        return (DigitalAssetRecipientIsCompany)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DigitalAssetRecipientIsIndividual`. If the actual instance is not `DigitalAssetRecipientIsIndividual`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DigitalAssetRecipientIsIndividual`
     * @throws ClassCastException if the instance is not `DigitalAssetRecipientIsIndividual`
     */
    public DigitalAssetRecipientIsIndividual getDigitalAssetRecipientIsIndividual() throws ClassCastException {
        return (DigitalAssetRecipientIsIndividual)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof DigitalAssetRecipientIsIndividual) {
        if (getActualInstance() != null) {
          joiner.add(((DigitalAssetRecipientIsIndividual)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof DigitalAssetRecipientIsCompany) {
        if (getActualInstance() != null) {
          joiner.add(((DigitalAssetRecipientIsCompany)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

