/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * DigitalAssetWalletTransactionDetail4
 */
@JsonPropertyOrder({
  DigitalAssetWalletTransactionDetail4.JSON_PROPERTY_CLIENT_REFERENCE_ID,
  DigitalAssetWalletTransactionDetail4.JSON_PROPERTY_INITIATING_PARTY_ID,
  DigitalAssetWalletTransactionDetail4.JSON_PROPERTY_TRANSACTION_AMOUNT,
  DigitalAssetWalletTransactionDetail4.JSON_PROPERTY_SENDER_SOURCE_OF_FUNDS,
  DigitalAssetWalletTransactionDetail4.JSON_PROPERTY_BUSINESS_APPLICATION_ID,
  DigitalAssetWalletTransactionDetail4.JSON_PROPERTY_SETTLEMENT_CURRENCY_CODE,
  DigitalAssetWalletTransactionDetail4.JSON_PROPERTY_TRANSACTION_CURRENCY_CODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class DigitalAssetWalletTransactionDetail4 {
  public static final String JSON_PROPERTY_CLIENT_REFERENCE_ID = "clientReferenceId";
  private String clientReferenceId;

  public static final String JSON_PROPERTY_INITIATING_PARTY_ID = "initiatingPartyId";
  private Long initiatingPartyId;

  public static final String JSON_PROPERTY_TRANSACTION_AMOUNT = "transactionAmount";
  private Double transactionAmount;

  public static final String JSON_PROPERTY_SENDER_SOURCE_OF_FUNDS = "senderSourceOfFunds";
  private String senderSourceOfFunds;

  public static final String JSON_PROPERTY_BUSINESS_APPLICATION_ID = "businessApplicationId";
  private String businessApplicationId;

  public static final String JSON_PROPERTY_SETTLEMENT_CURRENCY_CODE = "settlementCurrencyCode";
  private String settlementCurrencyCode;

  public static final String JSON_PROPERTY_TRANSACTION_CURRENCY_CODE = "transactionCurrencyCode";
  private String transactionCurrencyCode;

  public DigitalAssetWalletTransactionDetail4() { 
  }

  public DigitalAssetWalletTransactionDetail4 clientReferenceId(String clientReferenceId) {
    this.clientReferenceId = clientReferenceId;
    return this;
  }

  /**
   * Identifier assigned by the Originating Entity to uniquely identify the transaction.  ISO20022 field name: Transaction Identification  Only alphanumeric and &#39;-&#39; characters are allowed. 
   * @return clientReferenceId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLIENT_REFERENCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getClientReferenceId() {
    return clientReferenceId;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_REFERENCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientReferenceId(String clientReferenceId) {
    this.clientReferenceId = clientReferenceId;
  }


  public DigitalAssetWalletTransactionDetail4 initiatingPartyId(Long initiatingPartyId) {
    this.initiatingPartyId = initiatingPartyId;
    return this;
  }

  /**
   * Identifier assigned by Visa to uniquely identify the Originating Entity who initiates the transaction  ISO20022 field name: Initiating Party Identification&lt;br&gt; Visa uses integer instead of string(1-35) for uniformed value generation and presentation. 
   * @return initiatingPartyId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INITIATING_PARTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getInitiatingPartyId() {
    return initiatingPartyId;
  }


  @JsonProperty(JSON_PROPERTY_INITIATING_PARTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInitiatingPartyId(Long initiatingPartyId) {
    this.initiatingPartyId = initiatingPartyId;
  }


  public DigitalAssetWalletTransactionDetail4 transactionAmount(Double transactionAmount) {
    this.transactionAmount = transactionAmount;
    return this;
  }

  /**
   * The amount to debit from merchant&#39;s funding account or credit to recipient&#39;s bank account. Note: Transaction amount can have decimal point for currencies that allow it. Refer to the Visa Direct Endpoint Guide for Payout on country-specific currency minor units.  Example: Currency exponent for USD is 2, the amount is $100.99. Currency exponent for JPY is 0. If the amount is JPY 10,000, then this field should populate “10000”. ISO20022 field name: Instructed Amount 
   * minimum: 0
   * @return transactionAmount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Double getTransactionAmount() {
    return transactionAmount;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionAmount(Double transactionAmount) {
    this.transactionAmount = transactionAmount;
  }


  public DigitalAssetWalletTransactionDetail4 senderSourceOfFunds(String senderSourceOfFunds) {
    this.senderSourceOfFunds = senderSourceOfFunds;
    return this;
  }

  /**
   * Sender source of funds indicator i.e. the funding method used by the sender to fund the payout.Valid values are: Conditional - source of funds is required by some endpoints, please check for Visa Payment Guide for details    01 &#x3D; Visa credit 02 &#x3D; Visa debit 03 &#x3D; Visa prepaid 04 &#x3D; Cash 05 &#x3D; Deposit accounts other than those linked to a Visa card (includes checking/savings accounts and proprietary debit/ATMcards) 06 &#x3D; Credit accounts other than those linked to a Visa card (includes credit cards and proprietary credit lines)  Note: For any Company to Company (C2C) or Company to Individual (C2I) use-case, this should be “05”, since the funds come from the sender’s bank account.  ISO20022 field name: Debtor Account Type 
   * @return senderSourceOfFunds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SENDER_SOURCE_OF_FUNDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSenderSourceOfFunds() {
    return senderSourceOfFunds;
  }


  @JsonProperty(JSON_PROPERTY_SENDER_SOURCE_OF_FUNDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSenderSourceOfFunds(String senderSourceOfFunds) {
    this.senderSourceOfFunds = senderSourceOfFunds;
  }


  public DigitalAssetWalletTransactionDetail4 businessApplicationId(String businessApplicationId) {
    this.businessApplicationId = businessApplicationId;
    return this;
  }

  /**
   * Business Application Identifier (BAI) identifies the type of program for which the payment is being sent, i.e. whether it is a funds disbursement, money transfer etc. It should be a valid value allowed by Visa and approved for the program during onboarding.  Valid BAI for Visa Direct Account &amp; Wallet:  - Money transfer: AA, PP, FT, WT;  - Non-money transfer: BB, FD, GD, GP, LO, MD, OG, PD, BP, PS; 
   * @return businessApplicationId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BUSINESS_APPLICATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBusinessApplicationId() {
    return businessApplicationId;
  }


  @JsonProperty(JSON_PROPERTY_BUSINESS_APPLICATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBusinessApplicationId(String businessApplicationId) {
    this.businessApplicationId = businessApplicationId;
  }


  public DigitalAssetWalletTransactionDetail4 settlementCurrencyCode(String settlementCurrencyCode) {
    this.settlementCurrencyCode = settlementCurrencyCode;
    return this;
  }

  /**
   * The settlement currency code The 3-character ISO-4217 code in this field reflects the currency for the Settlement amount to be debited from Originating Entity/Visa Client&#39;s funding account. Format: 3-character ISO-4217 (Alpha-3) currency code  &lt;b&gt;This field is mandatory&lt;/b&gt;  Example: GBP 
   * @return settlementCurrencyCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SETTLEMENT_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSettlementCurrencyCode() {
    return settlementCurrencyCode;
  }


  @JsonProperty(JSON_PROPERTY_SETTLEMENT_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSettlementCurrencyCode(String settlementCurrencyCode) {
    this.settlementCurrencyCode = settlementCurrencyCode;
  }


  public DigitalAssetWalletTransactionDetail4 transactionCurrencyCode(String transactionCurrencyCode) {
    this.transactionCurrencyCode = transactionCurrencyCode;
    return this;
  }

  /**
   * The 3-character ISO-4217 code in this field reflects the currency associated to the transaction amount.  Format: 3-character ISO-4217 (Alpha-3) currency code Example: PHP 
   * @return transactionCurrencyCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTransactionCurrencyCode() {
    return transactionCurrencyCode;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionCurrencyCode(String transactionCurrencyCode) {
    this.transactionCurrencyCode = transactionCurrencyCode;
  }


  /**
   * Return true if this DigitalAssetWalletTransactionDetail-4 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DigitalAssetWalletTransactionDetail4 digitalAssetWalletTransactionDetail4 = (DigitalAssetWalletTransactionDetail4) o;
    return Objects.equals(this.clientReferenceId, digitalAssetWalletTransactionDetail4.clientReferenceId) &&
        Objects.equals(this.initiatingPartyId, digitalAssetWalletTransactionDetail4.initiatingPartyId) &&
        Objects.equals(this.transactionAmount, digitalAssetWalletTransactionDetail4.transactionAmount) &&
        Objects.equals(this.senderSourceOfFunds, digitalAssetWalletTransactionDetail4.senderSourceOfFunds) &&
        Objects.equals(this.businessApplicationId, digitalAssetWalletTransactionDetail4.businessApplicationId) &&
        Objects.equals(this.settlementCurrencyCode, digitalAssetWalletTransactionDetail4.settlementCurrencyCode) &&
        Objects.equals(this.transactionCurrencyCode, digitalAssetWalletTransactionDetail4.transactionCurrencyCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientReferenceId, initiatingPartyId, transactionAmount, senderSourceOfFunds, businessApplicationId, settlementCurrencyCode, transactionCurrencyCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DigitalAssetWalletTransactionDetail4 {\n");
    sb.append("    clientReferenceId: ").append(toIndentedString(clientReferenceId)).append("\n");
    sb.append("    initiatingPartyId: ").append(toIndentedString(initiatingPartyId)).append("\n");
    sb.append("    transactionAmount: ").append(toIndentedString(transactionAmount)).append("\n");
    sb.append("    senderSourceOfFunds: ").append(toIndentedString(senderSourceOfFunds)).append("\n");
    sb.append("    businessApplicationId: ").append(toIndentedString(businessApplicationId)).append("\n");
    sb.append("    settlementCurrencyCode: ").append(toIndentedString(settlementCurrencyCode)).append("\n");
    sb.append("    transactionCurrencyCode: ").append(toIndentedString(transactionCurrencyCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `clientReferenceId` to the URL query string
    if (getClientReferenceId() != null) {
      joiner.add(String.format("%sclientReferenceId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getClientReferenceId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `initiatingPartyId` to the URL query string
    if (getInitiatingPartyId() != null) {
      joiner.add(String.format("%sinitiatingPartyId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getInitiatingPartyId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `transactionAmount` to the URL query string
    if (getTransactionAmount() != null) {
      joiner.add(String.format("%stransactionAmount%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTransactionAmount()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `senderSourceOfFunds` to the URL query string
    if (getSenderSourceOfFunds() != null) {
      joiner.add(String.format("%ssenderSourceOfFunds%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSenderSourceOfFunds()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `businessApplicationId` to the URL query string
    if (getBusinessApplicationId() != null) {
      joiner.add(String.format("%sbusinessApplicationId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getBusinessApplicationId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `settlementCurrencyCode` to the URL query string
    if (getSettlementCurrencyCode() != null) {
      joiner.add(String.format("%ssettlementCurrencyCode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSettlementCurrencyCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `transactionCurrencyCode` to the URL query string
    if (getTransactionCurrencyCode() != null) {
      joiner.add(String.format("%stransactionCurrencyCode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTransactionCurrencyCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

