/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * FieldClientDriven
 */
@JsonPropertyOrder({
  FieldClientDriven.JSON_PROPERTY_$_REF,
  FieldClientDriven.JSON_PROPERTY_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class FieldClientDriven {
  public static final String JSON_PROPERTY_$_REF = "$ref";
  private String $ref;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public FieldClientDriven() { 
  }

  public FieldClientDriven $ref(String $ref) {
    this.$ref = $ref;
    return this;
  }

  /**
   * this refers to a JSON Schema definition within the document
   * @return $ref
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_$_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String get$Ref() {
    return $ref;
  }


  @JsonProperty(JSON_PROPERTY_$_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void set$Ref(String $ref) {
    this.$ref = $ref;
  }


  public FieldClientDriven name(String name) {
    this.name = name;
    return this;
  }

  /**
   * This field contains full JSON path (with &#39;$&#39; at the beginning) of the field in Send Payout API.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  /**
   * Return true if this FieldClientDriven object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldClientDriven fieldClientDriven = (FieldClientDriven) o;
    return Objects.equals(this.$ref, fieldClientDriven.$ref) &&
        Objects.equals(this.name, fieldClientDriven.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash($ref, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldClientDriven {\n");
    sb.append("    $ref: ").append(toIndentedString($ref)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `$ref` to the URL query string
    if (get$Ref() != null) {
      joiner.add(String.format("%s$ref%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(get$Ref()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

