/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.PayoutDigitalAssetRequestAlteredRecipientDetail;
import com.example.transformation.dto.visa.PayoutDigitalAssetRequestAlteredSenderDetail;
import com.example.transformation.dto.visa.PayoutMethod;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * PayoutDigitalAssetRequest1
 */
@JsonPropertyOrder({
  PayoutDigitalAssetRequest1.JSON_PROPERTY_PAYOUT_METHOD,
  PayoutDigitalAssetRequest1.JSON_PROPERTY_SENDER_DETAIL,
  PayoutDigitalAssetRequest1.JSON_PROPERTY_RECIPIENT_DETAIL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class PayoutDigitalAssetRequest1 {
  public static final String JSON_PROPERTY_PAYOUT_METHOD = "payoutMethod";
  private PayoutMethod payoutMethod;

  public static final String JSON_PROPERTY_SENDER_DETAIL = "senderDetail";
  private PayoutDigitalAssetRequestAlteredSenderDetail senderDetail;

  public static final String JSON_PROPERTY_RECIPIENT_DETAIL = "recipientDetail";
  private PayoutDigitalAssetRequestAlteredRecipientDetail recipientDetail;

  public PayoutDigitalAssetRequest1() { 
  }

  public PayoutDigitalAssetRequest1 payoutMethod(PayoutMethod payoutMethod) {
    this.payoutMethod = payoutMethod;
    return this;
  }

  /**
   * Originating Entity must indicate the payout method i.e. Digital Asset  Valid values: \&quot;D\&quot; – Visa Direct Digital Asset 
   * @return payoutMethod
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYOUT_METHOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PayoutMethod getPayoutMethod() {
    return payoutMethod;
  }


  @JsonProperty(JSON_PROPERTY_PAYOUT_METHOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayoutMethod(PayoutMethod payoutMethod) {
    this.payoutMethod = payoutMethod;
  }


  public PayoutDigitalAssetRequest1 senderDetail(PayoutDigitalAssetRequestAlteredSenderDetail senderDetail) {
    this.senderDetail = senderDetail;
    return this;
  }

  /**
   * Get senderDetail
   * @return senderDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SENDER_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PayoutDigitalAssetRequestAlteredSenderDetail getSenderDetail() {
    return senderDetail;
  }


  @JsonProperty(JSON_PROPERTY_SENDER_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSenderDetail(PayoutDigitalAssetRequestAlteredSenderDetail senderDetail) {
    this.senderDetail = senderDetail;
  }


  public PayoutDigitalAssetRequest1 recipientDetail(PayoutDigitalAssetRequestAlteredRecipientDetail recipientDetail) {
    this.recipientDetail = recipientDetail;
    return this;
  }

  /**
   * Get recipientDetail
   * @return recipientDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RECIPIENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PayoutDigitalAssetRequestAlteredRecipientDetail getRecipientDetail() {
    return recipientDetail;
  }


  @JsonProperty(JSON_PROPERTY_RECIPIENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecipientDetail(PayoutDigitalAssetRequestAlteredRecipientDetail recipientDetail) {
    this.recipientDetail = recipientDetail;
  }


  /**
   * Return true if this PayoutDigitalAssetRequest-1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayoutDigitalAssetRequest1 payoutDigitalAssetRequest1 = (PayoutDigitalAssetRequest1) o;
    return Objects.equals(this.payoutMethod, payoutDigitalAssetRequest1.payoutMethod) &&
        Objects.equals(this.senderDetail, payoutDigitalAssetRequest1.senderDetail) &&
        Objects.equals(this.recipientDetail, payoutDigitalAssetRequest1.recipientDetail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payoutMethod, senderDetail, recipientDetail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayoutDigitalAssetRequest1 {\n");
    sb.append("    payoutMethod: ").append(toIndentedString(payoutMethod)).append("\n");
    sb.append("    senderDetail: ").append(toIndentedString(senderDetail)).append("\n");
    sb.append("    recipientDetail: ").append(toIndentedString(recipientDetail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `payoutMethod` to the URL query string
    if (getPayoutMethod() != null) {
      joiner.add(String.format("%spayoutMethod%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPayoutMethod()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `senderDetail` to the URL query string
    if (getSenderDetail() != null) {
      joiner.add(getSenderDetail().toUrlQueryString(prefix + "senderDetail" + suffix));
    }

    // add `recipientDetail` to the URL query string
    if (getRecipientDetail() != null) {
      joiner.add(getRecipientDetail().toUrlQueryString(prefix + "recipientDetail" + suffix));
    }

    return joiner.toString();
  }
}

