/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.RecipientIdentificationList2Inner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * PayoutWalletRequest8RecipientDetailIdentificationList
 */
@JsonPropertyOrder({
  PayoutWalletRequest8RecipientDetailIdentificationList.JSON_PROPERTY_ID_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class PayoutWalletRequest8RecipientDetailIdentificationList {
  public static final String JSON_PROPERTY_ID_TYPE = "idType";
  private Object idType = null;

  public PayoutWalletRequest8RecipientDetailIdentificationList() { 
  }

  public PayoutWalletRequest8RecipientDetailIdentificationList idType(Object idType) {
    this.idType = idType;
    return this;
  }

  /**
   * Recipient identification type (issued by a government or similar authority) needs to be provided by Originating Entity along with the payment in certain markets.   Valid values :  * P- Passport  * D-Driving License  * N-National Id  * T-Tax Id  * L-Legal Entity Registration Number  * F-Foreign Id  Conditional (Refer to Payouts Endpoint Guide on country-specific required fields and lengths)  ISO20022 field name: Creditor Identification Code 
   * @return idType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getIdType() {
    return idType;
  }


  @JsonProperty(JSON_PROPERTY_ID_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdType(Object idType) {
    this.idType = idType;
  }


  /**
   * Return true if this PayoutWalletRequest_8_recipientDetail_identificationList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayoutWalletRequest8RecipientDetailIdentificationList payoutWalletRequest8RecipientDetailIdentificationList = (PayoutWalletRequest8RecipientDetailIdentificationList) o;
    return Objects.equals(this.idType, payoutWalletRequest8RecipientDetailIdentificationList.idType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayoutWalletRequest8RecipientDetailIdentificationList {\n");
    sb.append("    idType: ").append(toIndentedString(idType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    return joiner.toString();
  }
}

