/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.QueryPayoutIdResponse2001OriginatorDetail;
import com.example.transformation.dto.visa.QueryPayoutIdResponse2001RecipientDetail;
import com.example.transformation.dto.visa.QueryPayoutIdResponse200TransactionDetail;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * QueryPayoutIdResponse200
 */
@JsonPropertyOrder({
  QueryPayoutIdResponse200.JSON_PROPERTY_RECIPIENT_DETAIL,
  QueryPayoutIdResponse200.JSON_PROPERTY_ORIGINATOR_DETAIL,
  QueryPayoutIdResponse200.JSON_PROPERTY_TRANSACTION_DETAIL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class QueryPayoutIdResponse200 {
  public static final String JSON_PROPERTY_RECIPIENT_DETAIL = "recipientDetail";
  private QueryPayoutIdResponse2001RecipientDetail recipientDetail;

  public static final String JSON_PROPERTY_ORIGINATOR_DETAIL = "originatorDetail";
  private QueryPayoutIdResponse2001OriginatorDetail originatorDetail;

  public static final String JSON_PROPERTY_TRANSACTION_DETAIL = "transactionDetail";
  private QueryPayoutIdResponse200TransactionDetail transactionDetail;

  public QueryPayoutIdResponse200() { 
  }

  public QueryPayoutIdResponse200 recipientDetail(QueryPayoutIdResponse2001RecipientDetail recipientDetail) {
    this.recipientDetail = recipientDetail;
    return this;
  }

  /**
   * Get recipientDetail
   * @return recipientDetail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECIPIENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public QueryPayoutIdResponse2001RecipientDetail getRecipientDetail() {
    return recipientDetail;
  }


  @JsonProperty(JSON_PROPERTY_RECIPIENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecipientDetail(QueryPayoutIdResponse2001RecipientDetail recipientDetail) {
    this.recipientDetail = recipientDetail;
  }


  public QueryPayoutIdResponse200 originatorDetail(QueryPayoutIdResponse2001OriginatorDetail originatorDetail) {
    this.originatorDetail = originatorDetail;
    return this;
  }

  /**
   * Get originatorDetail
   * @return originatorDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORIGINATOR_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public QueryPayoutIdResponse2001OriginatorDetail getOriginatorDetail() {
    return originatorDetail;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINATOR_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOriginatorDetail(QueryPayoutIdResponse2001OriginatorDetail originatorDetail) {
    this.originatorDetail = originatorDetail;
  }


  public QueryPayoutIdResponse200 transactionDetail(QueryPayoutIdResponse200TransactionDetail transactionDetail) {
    this.transactionDetail = transactionDetail;
    return this;
  }

  /**
   * Get transactionDetail
   * @return transactionDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public QueryPayoutIdResponse200TransactionDetail getTransactionDetail() {
    return transactionDetail;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionDetail(QueryPayoutIdResponse200TransactionDetail transactionDetail) {
    this.transactionDetail = transactionDetail;
  }


  /**
   * Return true if this QueryPayoutIdResponse200 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryPayoutIdResponse200 queryPayoutIdResponse200 = (QueryPayoutIdResponse200) o;
    return Objects.equals(this.recipientDetail, queryPayoutIdResponse200.recipientDetail) &&
        Objects.equals(this.originatorDetail, queryPayoutIdResponse200.originatorDetail) &&
        Objects.equals(this.transactionDetail, queryPayoutIdResponse200.transactionDetail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recipientDetail, originatorDetail, transactionDetail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryPayoutIdResponse200 {\n");
    sb.append("    recipientDetail: ").append(toIndentedString(recipientDetail)).append("\n");
    sb.append("    originatorDetail: ").append(toIndentedString(originatorDetail)).append("\n");
    sb.append("    transactionDetail: ").append(toIndentedString(transactionDetail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `recipientDetail` to the URL query string
    if (getRecipientDetail() != null) {
      joiner.add(getRecipientDetail().toUrlQueryString(prefix + "recipientDetail" + suffix));
    }

    // add `originatorDetail` to the URL query string
    if (getOriginatorDetail() != null) {
      joiner.add(getOriginatorDetail().toUrlQueryString(prefix + "originatorDetail" + suffix));
    }

    // add `transactionDetail` to the URL query string
    if (getTransactionDetail() != null) {
      joiner.add(getTransactionDetail().toUrlQueryString(prefix + "transactionDetail" + suffix));
    }

    return joiner.toString();
  }
}

