/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * This field will contain values that identifies the type of service assigned for the transaction.
 */
@JsonPropertyOrder({
  QueryPayoutIdResponse2001TransactionDetailServiceProcessingType.JSON_PROPERTY_REQUEST_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class QueryPayoutIdResponse2001TransactionDetailServiceProcessingType {
  public static final String JSON_PROPERTY_REQUEST_TYPE = "requestType";
  private String requestType;

  public QueryPayoutIdResponse2001TransactionDetailServiceProcessingType() { 
  }

  public QueryPayoutIdResponse2001TransactionDetailServiceProcessingType requestType(String requestType) {
    this.requestType = requestType;
    return this;
  }

  /**
   * Reserved for future use.&lt;/br&gt;&lt;/br&gt;P2A: N/A P2C: Optional
   * @return requestType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REQUEST_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRequestType() {
    return requestType;
  }


  @JsonProperty(JSON_PROPERTY_REQUEST_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestType(String requestType) {
    this.requestType = requestType;
  }


  /**
   * Return true if this QueryPayoutIdResponse200_1_transactionDetail_serviceProcessingType object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryPayoutIdResponse2001TransactionDetailServiceProcessingType queryPayoutIdResponse2001TransactionDetailServiceProcessingType = (QueryPayoutIdResponse2001TransactionDetailServiceProcessingType) o;
    return Objects.equals(this.requestType, queryPayoutIdResponse2001TransactionDetailServiceProcessingType.requestType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryPayoutIdResponse2001TransactionDetailServiceProcessingType {\n");
    sb.append("    requestType: ").append(toIndentedString(requestType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `requestType` to the URL query string
    if (getRequestType() != null) {
      joiner.add(String.format("%srequestType%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRequestType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

