/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * SendPayoutFromOriginatorRequestTransactionDetailSettlement
 */
@JsonPropertyOrder({
  SendPayoutFromOriginatorRequestTransactionDetailSettlement.JSON_PROPERTY_SERVICE_INDICATOR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class SendPayoutFromOriginatorRequestTransactionDetailSettlement {
  public static final String JSON_PROPERTY_SERVICE_INDICATOR = "serviceIndicator";
  private String serviceIndicator;

  public SendPayoutFromOriginatorRequestTransactionDetailSettlement() { 
  }

  public SendPayoutFromOriginatorRequestTransactionDetailSettlement serviceIndicator(String serviceIndicator) {
    this.serviceIndicator = serviceIndicator;
    return this;
  }

  /**
   * This flag enables the originator to request for a particular settlement service to be used for settling the transaction. &lt;br&gt;&lt;br&gt; Valid values are: &lt;br&gt;0 - International Settlement&lt;br&gt;9 - VIP to decide&lt;br&gt;8 - National Settlement&lt;br&gt;&lt;br&gt;&lt;b&gt;Note:&lt;/b&gt; The default value is 9. This field is only relevant for specific countries where the acquirer has to select 8 in order to settle in the national net settlement service. 
   * @return serviceIndicator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE_INDICATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getServiceIndicator() {
    return serviceIndicator;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_INDICATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceIndicator(String serviceIndicator) {
    this.serviceIndicator = serviceIndicator;
  }


  /**
   * Return true if this SendPayoutFromOriginatorRequest_transactionDetail_settlement object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendPayoutFromOriginatorRequestTransactionDetailSettlement sendPayoutFromOriginatorRequestTransactionDetailSettlement = (SendPayoutFromOriginatorRequestTransactionDetailSettlement) o;
    return Objects.equals(this.serviceIndicator, sendPayoutFromOriginatorRequestTransactionDetailSettlement.serviceIndicator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceIndicator);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendPayoutFromOriginatorRequestTransactionDetailSettlement {\n");
    sb.append("    serviceIndicator: ").append(toIndentedString(serviceIndicator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `serviceIndicator` to the URL query string
    if (getServiceIndicator() != null) {
      joiner.add(String.format("%sserviceIndicator%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getServiceIndicator()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

