/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * ServiceDetail1
 */
@JsonPropertyOrder({
  ServiceDetail1.JSON_PROPERTY_TRACEABLE,
  ServiceDetail1.JSON_PROPERTY_RECALLABLE,
  ServiceDetail1.JSON_PROPERTY_PAYMENT_RAIL,
  ServiceDetail1.JSON_PROPERTY_IS_FINAL_STATUS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class ServiceDetail1 {
  public static final String JSON_PROPERTY_TRACEABLE = "traceable";
  private Boolean traceable;

  public static final String JSON_PROPERTY_RECALLABLE = "recallable";
  private Boolean recallable;

  /**
   * Indicates the payment rail used for the payout transaction
   */
  public enum PaymentRailEnum {
    ACH("ACH"),
    
    RTP("RTP"),
    
    RTGS("RTGS"),
    
    SWIFT("SWIFT");

    private String value;

    PaymentRailEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PaymentRailEnum fromValue(String value) {
      for (PaymentRailEnum b : PaymentRailEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PAYMENT_RAIL = "paymentRail";
  private PaymentRailEnum paymentRail;

  public static final String JSON_PROPERTY_IS_FINAL_STATUS = "isFinalStatus";
  private Boolean isFinalStatus;

  public ServiceDetail1() { 
  }

  public ServiceDetail1 traceable(Boolean traceable) {
    this.traceable = traceable;
    return this;
  }

  /**
   * Indicates if a payout transaction is traceable
   * @return traceable
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACEABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getTraceable() {
    return traceable;
  }


  @JsonProperty(JSON_PROPERTY_TRACEABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTraceable(Boolean traceable) {
    this.traceable = traceable;
  }


  public ServiceDetail1 recallable(Boolean recallable) {
    this.recallable = recallable;
    return this;
  }

  /**
   * Indicates if a payout transaction is recallable
   * @return recallable
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECALLABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getRecallable() {
    return recallable;
  }


  @JsonProperty(JSON_PROPERTY_RECALLABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecallable(Boolean recallable) {
    this.recallable = recallable;
  }


  public ServiceDetail1 paymentRail(PaymentRailEnum paymentRail) {
    this.paymentRail = paymentRail;
    return this;
  }

  /**
   * Indicates the payment rail used for the payout transaction
   * @return paymentRail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_RAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PaymentRailEnum getPaymentRail() {
    return paymentRail;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_RAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentRail(PaymentRailEnum paymentRail) {
    this.paymentRail = paymentRail;
  }


  public ServiceDetail1 isFinalStatus(Boolean isFinalStatus) {
    this.isFinalStatus = isFinalStatus;
    return this;
  }

  /**
   * Only populated at PAYMENT_SENT status. If &#39;false&#39; indicates that network partner will provide any of the following status &#39;PAYMENT_DELIVERED&#39;, &#39;DELIVERED_TO_SCHEME&#39;, &#39;DELIVERED_TO_RECIPIENT_BANK&#39;.
   * @return isFinalStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_FINAL_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsFinalStatus() {
    return isFinalStatus;
  }


  @JsonProperty(JSON_PROPERTY_IS_FINAL_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsFinalStatus(Boolean isFinalStatus) {
    this.isFinalStatus = isFinalStatus;
  }


  /**
   * Return true if this ServiceDetail-1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceDetail1 serviceDetail1 = (ServiceDetail1) o;
    return Objects.equals(this.traceable, serviceDetail1.traceable) &&
        Objects.equals(this.recallable, serviceDetail1.recallable) &&
        Objects.equals(this.paymentRail, serviceDetail1.paymentRail) &&
        Objects.equals(this.isFinalStatus, serviceDetail1.isFinalStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(traceable, recallable, paymentRail, isFinalStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceDetail1 {\n");
    sb.append("    traceable: ").append(toIndentedString(traceable)).append("\n");
    sb.append("    recallable: ").append(toIndentedString(recallable)).append("\n");
    sb.append("    paymentRail: ").append(toIndentedString(paymentRail)).append("\n");
    sb.append("    isFinalStatus: ").append(toIndentedString(isFinalStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `traceable` to the URL query string
    if (getTraceable() != null) {
      joiner.add(String.format("%straceable%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTraceable()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `recallable` to the URL query string
    if (getRecallable() != null) {
      joiner.add(String.format("%srecallable%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRecallable()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `paymentRail` to the URL query string
    if (getPaymentRail() != null) {
      joiner.add(String.format("%spaymentRail%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPaymentRail()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `isFinalStatus` to the URL query string
    if (getIsFinalStatus() != null) {
      joiner.add(String.format("%sisFinalStatus%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getIsFinalStatus()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

