/*
 * Visa Direct Account and Wallet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.transformation.dto.visa;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.transformation.dto.visa.PayoutToAccountRequestRecipientDetail;
import com.example.transformation.dto.visa.PayoutToAccountRequestSenderDetail;
import com.example.transformation.dto.visa.ValidateAccountTransactionDetail1;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.example.transformation.dto.ApiClient;
/**
 * ValidatePayoutAccountOnlyRequest
 */
@JsonPropertyOrder({
  ValidatePayoutAccountOnlyRequest.JSON_PROPERTY_TRANSACTION_DETAIL,
  ValidatePayoutAccountOnlyRequest.JSON_PROPERTY_ACCOUNT_VERIFICATION_REQUIRED,
  ValidatePayoutAccountOnlyRequest.JSON_PROPERTY_PAYOUT_METHOD,
  ValidatePayoutAccountOnlyRequest.JSON_PROPERTY_SENDER_DETAIL,
  ValidatePayoutAccountOnlyRequest.JSON_PROPERTY_RECIPIENT_DETAIL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-10T20:13:57.632250+05:30[Asia/Kolkata]", comments = "Generator version: 7.7.0")
public class ValidatePayoutAccountOnlyRequest {
  public static final String JSON_PROPERTY_TRANSACTION_DETAIL = "transactionDetail";
  private ValidateAccountTransactionDetail1 transactionDetail;

  public static final String JSON_PROPERTY_ACCOUNT_VERIFICATION_REQUIRED = "accountVerificationRequired";
  private Boolean accountVerificationRequired;

  /**
   * Originating Entity must indicate the payout method i.e. To Account   Valid values: “B” – Visa Direct Account 
   */
  public enum PayoutMethodEnum {
    B("B");

    private String value;

    PayoutMethodEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PayoutMethodEnum fromValue(String value) {
      for (PayoutMethodEnum b : PayoutMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PAYOUT_METHOD = "payoutMethod";
  private PayoutMethodEnum payoutMethod;

  public static final String JSON_PROPERTY_SENDER_DETAIL = "senderDetail";
  private PayoutToAccountRequestSenderDetail senderDetail;

  public static final String JSON_PROPERTY_RECIPIENT_DETAIL = "recipientDetail";
  private PayoutToAccountRequestRecipientDetail recipientDetail;

  public ValidatePayoutAccountOnlyRequest() { 
  }

  public ValidatePayoutAccountOnlyRequest transactionDetail(ValidateAccountTransactionDetail1 transactionDetail) {
    this.transactionDetail = transactionDetail;
    return this;
  }

  /**
   * Get transactionDetail
   * @return transactionDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ValidateAccountTransactionDetail1 getTransactionDetail() {
    return transactionDetail;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionDetail(ValidateAccountTransactionDetail1 transactionDetail) {
    this.transactionDetail = transactionDetail;
  }


  public ValidatePayoutAccountOnlyRequest accountVerificationRequired(Boolean accountVerificationRequired) {
    this.accountVerificationRequired = accountVerificationRequired;
    return this;
  }

  /**
   * Indicates whether account verification services are required.If True, account will be verified.If False, account verification will be skipped. Applicable only for Accounts.
   * @return accountVerificationRequired
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_VERIFICATION_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getAccountVerificationRequired() {
    return accountVerificationRequired;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_VERIFICATION_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountVerificationRequired(Boolean accountVerificationRequired) {
    this.accountVerificationRequired = accountVerificationRequired;
  }


  public ValidatePayoutAccountOnlyRequest payoutMethod(PayoutMethodEnum payoutMethod) {
    this.payoutMethod = payoutMethod;
    return this;
  }

  /**
   * Originating Entity must indicate the payout method i.e. To Account   Valid values: “B” – Visa Direct Account 
   * @return payoutMethod
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYOUT_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PayoutMethodEnum getPayoutMethod() {
    return payoutMethod;
  }


  @JsonProperty(JSON_PROPERTY_PAYOUT_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayoutMethod(PayoutMethodEnum payoutMethod) {
    this.payoutMethod = payoutMethod;
  }


  public ValidatePayoutAccountOnlyRequest senderDetail(PayoutToAccountRequestSenderDetail senderDetail) {
    this.senderDetail = senderDetail;
    return this;
  }

  /**
   * Get senderDetail
   * @return senderDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SENDER_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PayoutToAccountRequestSenderDetail getSenderDetail() {
    return senderDetail;
  }


  @JsonProperty(JSON_PROPERTY_SENDER_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSenderDetail(PayoutToAccountRequestSenderDetail senderDetail) {
    this.senderDetail = senderDetail;
  }


  public ValidatePayoutAccountOnlyRequest recipientDetail(PayoutToAccountRequestRecipientDetail recipientDetail) {
    this.recipientDetail = recipientDetail;
    return this;
  }

  /**
   * Get recipientDetail
   * @return recipientDetail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RECIPIENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PayoutToAccountRequestRecipientDetail getRecipientDetail() {
    return recipientDetail;
  }


  @JsonProperty(JSON_PROPERTY_RECIPIENT_DETAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecipientDetail(PayoutToAccountRequestRecipientDetail recipientDetail) {
    this.recipientDetail = recipientDetail;
  }


  /**
   * Return true if this ValidatePayoutAccountOnlyRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidatePayoutAccountOnlyRequest validatePayoutAccountOnlyRequest = (ValidatePayoutAccountOnlyRequest) o;
    return Objects.equals(this.transactionDetail, validatePayoutAccountOnlyRequest.transactionDetail) &&
        Objects.equals(this.accountVerificationRequired, validatePayoutAccountOnlyRequest.accountVerificationRequired) &&
        Objects.equals(this.payoutMethod, validatePayoutAccountOnlyRequest.payoutMethod) &&
        Objects.equals(this.senderDetail, validatePayoutAccountOnlyRequest.senderDetail) &&
        Objects.equals(this.recipientDetail, validatePayoutAccountOnlyRequest.recipientDetail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionDetail, accountVerificationRequired, payoutMethod, senderDetail, recipientDetail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidatePayoutAccountOnlyRequest {\n");
    sb.append("    transactionDetail: ").append(toIndentedString(transactionDetail)).append("\n");
    sb.append("    accountVerificationRequired: ").append(toIndentedString(accountVerificationRequired)).append("\n");
    sb.append("    payoutMethod: ").append(toIndentedString(payoutMethod)).append("\n");
    sb.append("    senderDetail: ").append(toIndentedString(senderDetail)).append("\n");
    sb.append("    recipientDetail: ").append(toIndentedString(recipientDetail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `payoutMethod` to the URL query string
    if (getPayoutMethod() != null) {
      joiner.add(String.format("%spayoutMethod%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPayoutMethod()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `senderDetail` to the URL query string
    if (getSenderDetail() != null) {
      joiner.add(getSenderDetail().toUrlQueryString(prefix + "senderDetail" + suffix));
    }

    // add `recipientDetail` to the URL query string
    if (getRecipientDetail() != null) {
      joiner.add(getRecipientDetail().toUrlQueryString(prefix + "recipientDetail" + suffix));
    }

    return joiner.toString();
  }
}

